### ISSUE TITLE
How add an application to the system tray?

### ISSUE THREAD

**Issue by huxiyu** [sciter-sdk/go-sciter#100]
can  the application hide to the system tray when i close the window ?

**Comment by pravic** [comment]
Sciter does not have system tray support (yet). You need some additional library to use it (like [systray](https://github.com/getlantern/systray) or [trayhost](https://github.com/cratonica/trayhost)). Or you can talk to the OS API directly (not the best way though).

**Comment by huxiyu** [comment]
Thank you! 
it's ok with systray.

meanwhile window hidden and shown code in .html file：
view.state = View.WINDOW_SHOWN;
view.state = View.WINDOW_HIDDEN;
