### ISSUE TITLE
OSX can`t build.

### ISSUE THREAD

**Issue by ruihuowayking** [sciter-sdk/go-sciter#102]
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fno-common -I $WORK/github.com/sciter-sdk/go-sciter/_obj/ -g -O2 -g -w -std=c11 -Iinclude -DPLAIN_API_ONLY -Iinclude -Iinclude -o $WORK/github.com/sciter-sdk/go-sciter/_obj/_cgo_export.o -c $WORK/github.com/sciter-sdk/go-sciter/_obj/_cgo_export.c
clang -I . -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fno-common -I $WORK/github.com/sciter-sdk/go-sciter/_obj/ -g -O2 -g -w -std=c11 -Iinclude -DPLAIN_API_ONLY -Iinclude -Iinclude -o $WORK/github.com/sciter-sdk/go-sciter/_obj/sciter.cgo2.o -c $WORK/github.com/sciter-sdk/go-sciter/_obj/sciter.cgo2.c
# github.com/sciter-sdk/go-sciter
cgo-gcc-prolog:1091:8: error: field has incomplete type 'VOID' (aka 'void')
cgo-gcc-prolog:1432:8: error: field has incomplete type 'VOID' (aka 'void')
==================================================================
``
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

this is my gcc version .how can i fix it

**Comment by pravic** [comment]
I'll close this in favor of #119.
