### ISSUE TITLE
can frame load rice html?

### ISSUE THREAD

**Issue by huxiyu** [sciter-sdk/go-sciter#103]
main.go

    package main

    import (
        gorice "github.com/GeertJohan/go.rice"
        "github.com/sciter-sdk/go-sciter/rice"
    )
    func main() {
        ...
        box, err := gorice.FindBox("res")
        ...
        // resource packing
        rice.HandleDataLoad(w.Sciter)
        ...
    }

main.html

    <html>
        <script type="text/tiscript">
            const frameContent = $(frame#content);
            frameContent.load("rice://res/view.htm");
        </script>
        <body>
            <frame#content></frame>
        </body>
    </html>

i know this is ok below, because it uses file://res/view.htm

    frameContent.load("res/view.htm"); 

how can i use rice to load .htm?

**Comment by huxiyu** [comment]
i read code. i find it's my code error. rice loads well. because i  redefine w.SetCallback() after rice.HandleDataLoad(w.Sciter). it covers SetCallback() in rice.HandleDataLoad() that contains load code.

**Comment by pravic** [comment]
:)
