### ISSUE TITLE
LoadFile error=2

### ISSUE THREAD

**Issue by LuciferDev** [sciter-sdk/go-sciter#104]
I'm on mac
When I try to use LoadFile on a build I get "error to load FILENAME file, error=2".
Files are on the same path as the executable. It works when running go run example.go but not when running go build
¿Am I using this wrong? ¿Do I need to embbed files to the binary?

**Comment by pravic** [comment]
Apparently it's a problem with paths. Examples are trying to load html from their current directory.

In general there are several ways to avoid that:

* use absolute path to load the main html; html itself can use relative paths
* use resource packaging like go.rice or packfolder from Sciter, or even zip archive
* embed html into your code as string

**Comment by LuciferDev** [comment]
Program tries to get example.html from my user folder so I have to use absolute path. Thanks!

**Comment by pravic** [comment]
You are welcome.
