### ISSUE TITLE
Generated executable file (.exe) can not show contents without HTML files(.html)

### ISSUE THREAD

**Issue by c101088** [sciter-sdk/go-sciter#105]
When i use "go build " to generate  executable files, this file can not show the correct contents without clearly knowing the directory of the HTML files. Dose go-sciter have some function to compile the HTML file to the binary file(executable file)  or i need to define another directory to store the HTML files which will be uesd in my program?

**Comment by pravic** [comment]
> Dose go-sciter have some function to compile the HTML file to the binary file

Yes, there are [options](https://github.com/sciter-sdk/go-sciter/issues/104#issuecomment-360018455). I have answered in #104 about them.

**Comment by c101088** [comment]
Thanks and sorry for repeating the issue.

**Comment by pravic** [comment]
It's okay.
