### ISSUE TITLE
How to load DLL files dynamically?

### ISSUE THREAD

**Issue by zhuwei** [sciter-sdk/go-sciter#108]
32bit sciter.dll or 64bit sciter.dll.....
no idea....

**Comment by pravic** [comment]
Your app is always built in one bitness (32 or 64). So distribute only one sciter.dll with it.
Or describe what you want to do.

**Comment by zhuwei** [comment]
I want app to automatically load DLL(32 or 64)

**Comment by pravic** [comment]
I understand, but Go code is not a script like Python, where you don't know will it be run under x86 or x64 interpreter. 

After you compiled your program, just place the corresponding sciter.dll near your executable (better way). Or you can _install_ the sciter.dll system-wide, but in case of Windows it will be the only `C:\Windows\syswow64` or `C:\Windows\sysnative` place. In Linux/OSX you can place it in `lib32`/`lib64` directories.

And anyway, you always can rename sciter.dll as sciter32.dll or sciter64.dll. Right now it requires go-sciter modification. Perhaps, we can fallback from sciter.dll (if not found) to sciter 32/64 dll as a second try.

**Comment by zhuwei** [comment]
Thank you very much!
