### ISSUE TITLE
Does go-sciter have an example of using Sciter Archive(bin/packfolder)?

### ISSUE THREAD

**Issue by libs3** [sciter-sdk/go-sciter#109]
Don't know how to call it?Thank you.

**Comment by pravic** [comment]
I am afraid it is not supported in Go bindings. It is better to go with go.rice at the moment.
Although it is just a couple of calls (`SciterOpenArchive(archive pointer, length)`, `SciterGetArchiveItem(archive handle, entry path, result, result length)`, it was not added to Go.

**Comment by libs3** [comment]
Thank you for your timely and enthusiastic reply, although it is a pity, but go-scanner is really great!

**Comment by pravic** [comment]
> but go-scanner is really great

go-what? :)

**Comment by pravic** [comment]
It does not, since #141. Also `packfolder` has Go support since SDK 4.1.6.
