### ISSUE TITLE
role="window-caption" is not working

### ISSUE THREAD

**Issue by Inkeliz** [sciter-sdk/go-sciter#110]
I create a window using:

```
window.New(sciter.SW_MAIN | sciter.SW_RESIZEABLE | sciter.SW_ALPHA | sciter.SW_OWNS_VM |  sciter.SW_ENABLE_DEBUG, sciter.NewRect(200, 200, 1200, 800))
```

I need to create a way to allow the user to move the window. I had found [this posting](https://sciter.com/html-window/), it says:

> role=window-caption – window caption element – user can drag the window by pressing mouse in it.

I test modifying a existing HTML, just including the `role`:

```
<aside role="window-caption">
      <!-- Content -->
</aside>
```

However it's not working. I can resize the window, because of the usage of `SW_RESIZEABLE`, but I can't move the window. 

I doing something wrong? Have an alternative to achieve the same behavior?

**Comment by pravic** [comment]
Could you make a minimal reproducible example please?

**Comment by Inkeliz** [comment]
I can, but I think is not necessary. The problem is because I don't set the `window-frame="solid"` on `<html>`. 

To simply, I have something like that:
```
<html>

<head>
    <title>Index</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        aside {
            width: 50px;
            height: calc(100% - 30px);
            float: left;
            background: #262626;
            position: relative;
            padding: 15px;
            color: aliceblue;
        }
        main {
            width: calc(100% - (80px + 30px));
            height: calc(100% - 30px);
            background: #f053cd;
            padding: 15px;
            margin: 0;
            float: left;
        }
    </style>
</head>

<body>
    <aside role="window-caption">
        Aside
    </aside>
    <main>
        Main
    </main>
</body>

</html>
```
I want to use the `<aside>` to move the window, like a _titlebar_. It will not work until I set `window-frame="solid"` on `<html>`.

Now, it works as expected, using `<html window-frame="solid" resizeable>` , everything is working. 👍

**Comment by Inkeliz** [comment]
I don't know if I need to open an new issue, because is another topic, but related.

When I double click in this `aside` (or where the `window-caption` is living), it set the window to fullscreen. There is a way to disable this behavior?

**Comment by pravic** [comment]
I think this is default behavior used to maximize window. You can set your double click handler and intercept it when it's sinking.

**Comment by pravic** [comment]
> It will not work until I set window-frame="solid" on <html>.

I woul say, until you set any `windows-frame` attribute different from `"standard"`.
