### ISSUE TITLE
Build not working with GO 1.10 version

### ISSUE THREAD

**Issue by Aukstkalnis** [sciter-sdk/go-sciter#111]
When building project, there is cgo error:
github.com/sciter-sdk/go-sciter: invalid flag in #cgo CFLAGS: -w
The terminal process terminated with exit code: 1

**Comment by pravic** [comment]
https://github.com/golang/go/wiki/InvalidFlag You can temporary allow that flag. However there are other issues with 1.10 compilation, I'll tru to fix them soon. Or you can take a bit of time and make a PR.

**Comment by Aukstkalnis** [comment]
For what purpose cgo flag is used any way? I deleted it and added some type casting to fix errors and it worked jut fine.

**Comment by pravic** [comment]
`-w`? To suppress warnings. If you fixed them, that's great.

**Comment by Aukstkalnis** [comment]
I created a pull request for this case. Hope it heps :)

**Comment by pravic** [comment]
It does. Big thanks!
