### ISSUE TITLE
Debug JS/CSS/HTML?

### ISSUE THREAD

**Issue by gcstang** [sciter-sdk/go-sciter#114]
Is there a way to utilize a debugger like one in chrome in order to see JavaScript values, data, debug it and so on?

**Comment by pravic** [comment]
Inspector in sciter sdk.

**Comment by pravic** [comment]
https://sciter.com/tag/inspector/

**Comment by gcstang** [comment]
@pravic I tried to run this and it immediately closes, is there something you have to do besides open it as an application on Mac?

**Comment by pravic** [comment]
Not that I am aware of. It should work. 
Have you tried any other apps from the sciter sdk?

**Comment by pravic** [comment]
cc @c-smile

**Comment by gcstang** [comment]
@pravic @cc-smile
I tried opening the mac application but it shuts down immediately.
Instead what I had to do whas run the internal binary from the command line like this:
./inspector.app/Contents/MacOS/inspector

**Comment by c-smile** [comment]
On Mac:

Create Sciter's window with [SW_ENABLE_DEBUG](https://github.com/c-smile/sciter-sdk/blob/master/include/sciter-x-def.h#L597) flag. 

1. start your application.
2. start inspector and follow steps explained on its window.

@gcstang  "tried to run this and it immediately closes".  What is _this_ here?

**Comment by c-smile** [comment]
> run the internal binary from the command line like this

Oh, yeah. On recent OSX versions they changed policy of running GUI executables. Can this be fixed by changing permissions somehow? I have no idea yet. I know It should be some way as you can re-compile inspector on your side and it will work without terminal.

**Comment by Chinyaev** [comment]
Hi!

What I do wrong? 

```
	sciter.SetOption(sciter.SCITER_SET_DEBUG_MODE, 1)

	w, _ := window.New(sciter.SW_TITLEBAR|sciter.SW_ENABLE_DEBUG|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN, sciter.NewRect(0, 0, fromPosLeft, formPosTop))

	w.SetOption(sciter.SCITER_SET_DEBUG_MODE, 1)
```
I start my app
Then I start inspector.app (it opens)
Then I press CTRL+SHIFT+I

And get error:
`Error: (undefined) has no property - DataSocket
        at @2@10.@289@37 (sciter:debug-peer.tis(294))
        at @2@10.@268@31 (sciter:debug-peer.tis(271))`

I tried call inspector from script, but it don't work too (same error).

**Comment by c-smile** [comment]
By default and for security reasons all communication and system probing functions accessible from script are disabled in Sciter. 

So you should have something like this call before using any other Sciter API: 

```
 SciterSetOption(NULL, SCITER_SET_SCRIPT_RUNTIME_FEATURES,
    ALLOW_FILE_IO |
    ALLOW_SOCKET_IO |
    ALLOW_EVAL |
    ALLOW_SYSINFO);
```
`ALLOW_SOCKET_IO` will enable `System.Net` namespace and so `System.Net.DataSocket`  used for communication of the debugee with the Inspector.

**Comment by Chinyaev** [comment]
Thank you very much for the answer and of course Sciter!

It helps me:
sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SOCKET_IO)
