### ISSUE TITLE
What `rice` does?

### ISSUE THREAD

**Issue by Inkeliz** [sciter-sdk/go-sciter#117]
I'm checking the `examples/handlers/handlers.go`, this file have this line:
```
rice.HandleDataLoad(w.Sciter)
```
https://github.com/sciter-sdk/go-sciter/blob/master/examples/handlers/handlers.go#L117

I remove this line, because is getting an error. Everything is working, far I see. What it was supposed to do, what is the problem for not use it?

**Comment by pravic** [comment]
https://github.com/GeertJohan/go.rice it's a resource packaging and handling library.

**Comment by pravic** [comment]
> I remove this line, because is getting an error.

What error?

**Comment by Inkeliz** [comment]
The problem ocurr because I don't have the rice (https://github.com/GeertJohan/go.rice), then I try to remove this line and works. 

I will take a look what the GeertJohan/go.rice is supposed to do.

**Comment by pravic** [comment]
Go must download and build all dependencies itself, unless you cloned this repository yourself.
