### ISSUE TITLE
field has incomplete type 'VOID' (aka 'void')?

### ISSUE THREAD

**Issue by vanniuner** [sciter-sdk/go-sciter#119]
HELP
i just use :
go run /go-sciter/examples/simple.go

but there have :
gopath/src/github.com/sciter-sdk/go-sciter/sciter.go:1118:8: error: field has incomplete type 'VOID' (aka 'void')
gopath/src/github.com/sciter-sdk/go-sciter/sciter.go:1459:8: error: field has incomplete type 'VOID' (aka 'void')

**Comment by vanniuner** [comment]
i just use ：
go run /go-sciter/examples/simple.go

**Comment by pravic** [comment]
https://github.com/sciter-sdk/go-sciter/blob/master/sciter.go#L1118

https://github.com/sciter-sdk/go-sciter/blob/master/sciter.go#L1459

There's nothing there. Do you build the latest version?

**Comment by pravic** [comment]
#31 has the same error.
Can you show your environment? OS, gcc, go versions?
