### ISSUE TITLE
How create one <input type="file">?

### ISSUE THREAD

**Issue by Inkeliz** [sciter-sdk/go-sciter#121]
I'm using the Sciter, with just Golang.

But seems that Sciter doesn't supports the `<input type="file">`, also the Go seems to be not capable to handle an event like "when user drop the file".

My goal is get the path of the file and read the data in golang. The user can select it using `<input type="file">` or, better, droping the file. 

For now, I'm using one `<input type="text">`, but the user need to copy and paste the path of the file, which is strange and it's not an good experience to the user.

**Comment by Inkeliz** [comment]
I found this [issue](https://github.com/sciter-sdk/go-sciter/issues/28), so I'm using this code:

    class DropZone : Element {
      event drag (evt) {
        if(evt.draggingDataType == #file) {
          return true;
        }
      }
      event drop (evt) {
        if(evt.draggingDataType == #file) {
          this.attributes["path"] = evt.dragging
          return true;
        }
      }
    }

So I can get the `path` attribute when the user click on button, in Golang. Have another way to achieve the same behavior without this script?

**Comment by pravic** [comment]
`DRAG_ENTER` & K°
