### ISSUE TITLE
Added Vendoring support to project, now sciter-x.h file not found

### ISSUE THREAD

**Issue by gcstang** [sciter-sdk/go-sciter#122]
I have the dylib in the project folder and I also tried setting the path to it via export DYLD_LIBRARY_PATH and still get this error unless I delete the vendor folder.

`go build .
main.tech.com/go/dupcheck/vendor/github.com/sciter-sdk/go-sciter
vendor/github.com/sciter-sdk/go-sciter/sciter.go:11:10: fatal error: 'sciter-x.h' file not found
#include "sciter-x.h"
         ^~~~~~~~~~~~
1 error generated.`

**Comment by pravic** [comment]
Sorry, I didn't notice this issue.

What does vendoring mean here? I am not a Go fellow.

**Comment by gcstang** [comment]
Vendoring is how dependencies are now being utilized in most projects either via govendor project or the dep project.  I'm currently using the govendor but either way a vendor folder is created and all dependent projects (imports) are put or copied into that location as well as the vendor.json file that defines what is in there.  If I keep the sciter-osx-64.dylib where it was working before hand(main project folder) then it's not found when this dependency structure is used.

**Comment by pravic** [comment]
Well, `DYLD_LIBRARY_PATH` and dylib are unrelated to the original issue ('sciter-x.h' file not found).

The `sciter.go` adds a [go-sciter/include](https://github.com/sciter-sdk/go-sciter/blob/b3664515661a1ebfd456015895f26435b86e0527/include) directory via a [CGO directive](https://github.com/sciter-sdk/go-sciter/blob/b3664515661a1ebfd456015895f26435b86e0527/sciter.go#L8).

Do you have that folder, actually? If yes, then the vendoring, probably, changes the root folder and `include` can't be found. In this case you need to figure out how to make CGO find that directory.

For example, it can be done via `CGO_CFLAGS='-Ivendor/github.com/sciter-sdk/go-sciter/include'` environment variable (adjust it to your path).

**Comment by gcstang** [comment]
@pravic I tried that during go build -x . and go run main.go and it's not working.

**Comment by pravic** [comment]
Okay, how can I reproduce? Step by step from the beginning.

**Comment by gcstang** [comment]
1. go get -u github.com/kardianos/govendor
[tstsciter.zip](https://github.com/sciter-sdk/go-sciter/files/1869746/tstsciter.zip)
2. Unzip attached zip file
3. cd tstsciter/
4. go run main.go

**Comment by pravic** [comment]
As I said, your tstsciter.zip does not have that folder (see tstsciter/vendor/github.com/sciter-sdk/go-sciter/).

**Comment by gcstang** [comment]
@pravic I'm also new to Go and not sure what else to try, I've used your suggestion with CGO_CFLAGS and it doesn't work either.  What creates or puts the header file into that location? 'sciter-x.h'

**Comment by pravic** [comment]
I believe, you should read the `govendor`'s documentation first. A quick search revealed some old issues like https://github.com/kardianos/govendor/issues/61, but may be they are outdated.

Can you copy the go-sciter/include directory manually in your vendored directory? It will work, I think.

If you want to do it right, then learn `govendor` itself.

**Comment by gcstang** [comment]
@pravic that got me on the correct track!  
Thank you, I had to remove the vendor for go-sciter and then add it with:
govendor add github.com/sciter-sdk/go-sciter/^

**Comment by pravic** [comment]
Okay :)
