### ISSUE TITLE
How to package assets?

### ISSUE THREAD

**Issue by kylepritchard** [sciter-sdk/go-sciter#124]
I have read in the issues that go-sciter supports go.rice out of the box. How can i use rice to package assets when building a binary? I have used rice successfully before when packaging an webapp by providing a _riceBox_ location, although it must be a different process when not serving http. I can see in handlers example that `rice.HandleDataLoad(w.Sciter)` is used but when building example it doesn't bundle any resources. I have tried a number of different things now and have hit a wall. Any help would be appreciated.

**Comment by pravic** [comment]
Honestly, I have never worked with go.rice (I am not a Go developer per se, I just support this repo).

Have you tried to follow [its instructions](https://github.com/GeertJohan/go.rice)? You can make a simple example based on it and add it here, so other people will know that it's definitely possible :)

**Comment by jinxmcg** [comment]
Here you go, a working example:
create a folder called resources and put simple.html in it.
outside this folder create this go program and compile it 
``` 
go build -ldflags -H=windowsgui main.go
``` 
the flags I used remove the cmd window
now you can run your without the resource folder

```
package main

import (
	"log"
	rice "github.com/GeertJohan/go.rice"
	sciter "github.com/sciter-sdk/go-sciter"
	window "github.com/sciter-sdk/go-sciter/window"
)

func main() {
	conf := rice.Config{
		LocateOrder: []rice.LocateMethod{rice.LocateEmbedded, rice.LocateAppended, rice.LocateFS},
	}
	box, err := conf.FindBox("resources")
	if err != nil {
		log.Fatalf("error opening rice.Box: %s\n", err)
	}

	w, err := window.New(sciter.SW_TITLEBAR|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN, nil)
	if err != nil {
		log.Fatal(err)
	}
	contentHTML, err := box.String("simple.html")
	if err != nil {
		log.Fatalf("could not read file contents as string: %s\n", err)
	}
	w.LoadHtml(contentHTML, "")
	w.SetTitle("Example")
	w.Show()
	w.Run()
}
```

**Comment by pravic** [comment]
@jinxmcg Thanks! However your code uses Go.Rice directly (via `.FindBox`, `.String`) while it can be used [completely transparent](https://github.com/sciter-sdk/go-sciter/blob/master/rice/rice.go).

Essentially, `rice.HandleDataLoad` reduces your example to the following three calls:

```go
	rice.HandleDataLoad(w.Sciter)
	tool.FindBox("res")
	w.LoadFile("rice://res/simple.html")
```

Here is a full source code:

```go
package main

import (
	"log"
	tool "github.com/GeertJohan/go.rice"
	sciter "github.com/sciter-sdk/go-sciter"
	rice "github.com/sciter-sdk/go-sciter/rice"
	window "github.com/sciter-sdk/go-sciter/window"
)

func main() {
	// As usual, create a sciter window.
	w, err := window.New(sciter.SW_TITLEBAR|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN, nil)
	if err != nil {
		log.Fatal(err)
	}

	// 1. Handle resources via sciter.rice loader.
	// It handles URLS like `file://box/` and `rice://box/`.
	rice.HandleDataLoad(w.Sciter)

	// 2. A dummy call to allow `go.rice` to package and register that folder.
	_, err = tool.FindBox("res")
	if err != nil {
		log.Fatal(err)
	}

	// 3. Load a packaged resource.
	err = w.LoadFile("rice://res/simple.html")
	if err != nil {
		log.Fatal(err)
	}
	w.SetTitle("Example")
	w.Show()
	w.Run()
}
```

How to make it work:

* install go.gice package and tool: `go get github.com/GeertJohan/go.rice`, `go get github.com/GeertJohan/go.rice/rice`
* build your project via `go build`
* embed resources into executable via `rice append /exec example.exe`
* now you can move your example to a different folder, it will work with its own embedded resources.

Although only the `rice append` is supported. I think it's worth to allow and `rice embed` as well.

**Comment by jinxmcg** [comment]
Thanks I will use this version!

**Comment by pravic** [comment]
No, you have to deal with templates via `rice` and `text/template` on your own.
