### ISSUE TITLE
How can i use metroUI css  in go-sciter.

### ISSUE THREAD

**Issue by zsdevX** [sciter-sdk/go-sciter#125]
I download metroui(css/js/font) from https://www.metroui.org.ua/. and found it do not work.

is there some way to use the css/js? 

or some css/js can make my html beautiful?

**Comment by zsdevX** [comment]
Test it:
step1： put the css in html header
`<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-all.min.css">`

run sciter.exe and load the html, the button become too small to see.

**Comment by pravic** [comment]
1) Sciter does not have JavaScript

2) There might be differences in CSS (like flex units vs flexbox, etc)

**Comment by zsdevX** [comment]
thanks.
