### ISSUE TITLE
Unable to install package in Ubuntu 16.04

### ISSUE THREAD

**Issue by AshfordN** [sciter-sdk/go-sciter#126]
I've followed the installation instructions for Linux, but when I execute the following command:

`go get github.com/sciter-sdk/go-sciter`

I get the following error at the end:

```
# github.com/sciter-sdk/go-sciter
Projects/golang/src/github.com/sciter-sdk/go-sciter/sciter.go:47: invalid indirect of _Ctype_struct__GtkWidget(unsafe.Pointer(uintptr(0))) (type _Ctype_struct__GtkWidget)
Projects/golang/src/github.com/sciter-sdk/go-sciter/sciter.go:47: cannot convert unsafe.Pointer(uintptr(0)) (type unsafe.Pointer) to type _Ctype_struct__GtkWidget
Projects/golang/src/github.com/sciter-sdk/go-sciter/sciter.go:405: cannot convert nil to type _Ctype_struct__GtkWidget
```

Also, It is worth noting that the installation instructions are slightly off. Where the instructions says:

> cd sciter-sdk/bin.gtk/

it should actually be:

> cd sciter-sdk/bin.gtk/{arch}

**Comment by pravic** [comment]
Yeah, it has been changed recently.

**Comment by pravic** [comment]
Is it works now?

**Comment by AshfordN** [comment]
Yeah it's working. I tested it before I did the PR.

**Comment by pravic** [comment]
Okay
