### ISSUE TITLE
window-blurbehind not working as expected

### ISSUE THREAD

**Issue by Inkeliz** [sciter-sdk/go-sciter#130]
I'm testing the `window-blurbehind` attribute. It have the exactly same behavior of the `window-frame="transparent"`.

I tested with the `samples/dialogs+windows`, from the SDK, using the following code:

```
package main

import (
	"github.com/sciter-sdk/go-sciter/window"
	"github.com/sciter-sdk/go-sciter"
)

func main() {
	w, err := window.New(sciter.SW_GLASSY, sciter.NewRect(200, 200, 900, 600))
	if err != nil {
		panic(err)
	}

	w.LoadFile("test-window.htm")

	w.Show()
	w.Run()
}
```

When clicked in "Detached glassy siderbar window", the sidebar is not "glassy" but simply transparent. I think it's not the correct behavior, [I take one screenshot of the result](https://prnt.sc/iy27fn). 

I already tested it in my code, instead of the sample itself, nothing glassy at all. Furthermore, I can't use `background: inherit` and apply some `filter: blur()`, it just not work. I already test with/without the `SW_ALPHA`, `SW_GLASSY`, `SW_MAIN`...

However, when I tested the same file with `sciter.exe` [it works](https://prnt.sc/iy2ixw), so I think it's a problem with the golang. :\

**Comment by pravic** [comment]
Confirmed.  It works with pysciter, but not in Go.

**Comment by pravic** [comment]
It seems the same for me. Windows 7, Go 1.10, Sciter 4.1.4

![image](https://user-images.githubusercontent.com/724639/38103822-18e7064c-3390-11e8-9aec-2105d9070e58.png)

**Comment by pravic** [comment]
> w.LoadFile("test-window.htm")

By the way, have you tried an absolute url here? Something like `file:///d:/sciter-sdk/samples/dialogs+windows/test-window.htm`.

**Comment by Inkeliz** [comment]
I have tested it now with `file:///c:/path/to/test-window.htm`, but nothing change. I'm using the same version (4.1.4) and with Golang 1.10, but I'm using Windows 10.

That is strange.

**Comment by pravic** [comment]
That's odd. It works in Win10 as you described: glassy with sciter.exe, transparent with Go. But: it is also transparent with sciter-dx.exe. I have no idea, why.

Win7 always shows a glassy window.

cc @c-smile

**Comment by c-smile** [comment]
sciter.exe includes manifest file where W10 compatibility is declared explicitly.
That blurbehind stuff is Windows version dependent. W7 does it differently than W10.

Manifest file used:

```
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:windowsSettings
         xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true/pm</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
        <application> 
            <!-- Windows 10 --> 
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
            <!-- Windows 8.1 -->
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <!-- Windows Vista -->
            <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
            <!-- Windows 7 -->
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
            <!-- Windows 8 -->
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
        </application> 
  </compatibility>
  <dependency>
      <dependentAssembly>
          <assemblyIdentity
              type="win32"
              name="Microsoft.Windows.Common-Controls"
              version="6.0.0.0"
              processorArchitecture="*"
              publicKeyToken="6595b64144ccf1df"
              language="*"
          />
      </dependentAssembly>
  </dependency>
</assembly>

```

**Comment by Inkeliz** [comment]
**It's works!**

![image](https://user-images.githubusercontent.com/4644332/38120590-514c4bae-33a0-11e8-96a6-a2584ff726d5.png)

---------------

I'm using the same manifest from @c-smile, creating one `dialogs+windows.exe.manifest`. After that, I  downloaded the [`rsrc`](https://github.com/akavel/rsrc)  and run:

    rsrc -manifest="dialogs+windows.exe.manifest" -arch="amd64"

Then, use `go build`. _I think the [`HTML Window`](https://sciter.com/html-window/) should mention it, because no other feature needs the custom manifest._
