### ISSUE TITLE
How much is the golang version of your go-sciter support?

### ISSUE THREAD

**Issue by twelveandone** [sciter-sdk/go-sciter#137]
Hello, I have some questions to ask you
How much is the golang version of your go-sciter support?

I use go1.5.3 windows/amd64 and TDM-GCC-64 in win10，but it can‘t work:

**Comment by pravic** [comment]
There were fixes to make Go 1.10 work and they have made go-sciter incompatible with previous Go versions. 

But I haven't tested the Go 1.9 version against the earlier ones (1.5 and so on). You can try to download this version: https://github.com/sciter-sdk/go-sciter/releases/tag/go-1.9

If you can fix the current version to make it work with Go 1.5-1.9 - it would be cool.

**Comment by twelveandone** [comment]
version: https://github.com/sciter-sdk/go-sciter/releases/tag/go-1.9 
I use go1.9 windows/amd64 and TDM-GCC-64 in win10，but it can‘t work:

runtime
C:\Go\src\runtime\lfstack_amd64.go:16:45: lfstackPack redeclared in this block
        previous declaration at C:\Go\src\runtime\lfstack_64bit.go:37:45
C:\Go\src\runtime\lfstack_amd64.go:20:51: lfstackUnpack redeclared in this block
        previous declaration at C:\Go\src\runtime\lfstack_64bit.go:41:33
C:\Go\src\runtime\os_windows.go:14:10: _NSIG redeclared in this block
        previous declaration at C:\Go\src\runtime\os2_windows.go:18:10
C:\Go\src\runtime\os_windows.go:61:2: _AddVectoredExceptionHandler redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: _CloseHandle redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: _CreateEventA redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: _CreateIoCompletionPort redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: _CreateThread redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: _CreateWaitableTimerA redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: _DuplicateHandle redeclared in this block
        previous declaration at C:\Go\src\runtime\os1_windows.go:52:2
C:\Go\src\runtime\os_windows.go:61:2: too many errors

**Comment by pravic** [comment]
These errors look unrelated to the go-sciter. Can't you just use Go 1.10 with mingw-64?

**Comment by twelveandone** [comment]
How do I perform go-sciter-go-1.9.zip on the local

**Comment by twelveandone** [comment]
Reinstall golang

now
WORK=C:\Users\ADMINI~1\AppData\Local\Temp\go-build623023306
mkdir -p $WORK\github.com\lxn\win\_obj\
mkdir -p $WORK\github.com\lxn\
cd C:\Go\gopath\src\github.com\lxn\win
"C:\\Go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\lxn\\win.a" -trimpath "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306" -goversion go1.9 -p github.com/lxn/win -complete -buildid e7a06001b9bf5e40ce9d8618729f32cc96e3088d -D _/C_/Go/gopath/src/github.com/lxn/win -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306" -pack "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\advapi32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\combobox.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\comctl32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\comdlg32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\datetimepicker.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\edit.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\gdi32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\gdiplus.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\header.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\kernel32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\listbox.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\listview.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\menu.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\ole32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\oleaut32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\oleaut32_amd64.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\opengl32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\pdh.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\shdocvw.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\shell32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\shobj.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\shobj_amd64.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\statusbar.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\syslink.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\tab.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\toolbar.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\tooltip.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\treeview.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\updown.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\user32.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\uxtheme.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\win.go" "C:\\Go\\gopath\\src\\github.com\\lxn\\win\\winspool.go"
mkdir -p C:\Go\gopath\pkg\windows_amd64\github.com\lxn\
mv $WORK\github.com\lxn\win.a C:\Go\gopath\pkg\windows_amd64\github.com\lxn\win.a
mkdir -p $WORK\github.com\twelveandone\go\_obj\
mkdir -p $WORK\github.com\twelveandone\
cd C:\Go\gopath\src\github.com\twelveandone\go
CGO_LDFLAGS="-g" "-O2" "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -importpath github.com/twelveandone/go -- -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" sciter.go sciter_windows.go types.go utils.go
cd $WORK
gcc -fdebug-prefix-map=a=b -c trivial.c
gcc -gno-record-gcc-switches -c trivial.c
cd $WORK\github.com\twelveandone\go\_obj
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_export.o" -c _cgo_export.c
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter.cgo2.o" -c sciter.cgo2.c
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter_windows.cgo2.o" -c sciter_windows.cgo2.c
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\types.cgo2.o" -c types.cgo2.c
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\utils.cgo2.o" -c utils.cgo2.c
cd C:\Go\gopath\src\github.com\twelveandone\go
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\callbacks.o" -c callbacks.c
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter-x-api.o" -c sciter-x-api.c
cd $WORK\github.com\twelveandone\go\_obj
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\" -g -O2 -g -w -std=c11 "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -DPLAIN_API_ONLY "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" "-IC:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\include" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_main.o" -c _cgo_main.c
cd C:\Go\gopath\src\github.com\twelveandone\go
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_main.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_export.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter_windows.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\types.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\utils.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\callbacks.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter-x-api.o" -g -O2
"C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -dynpackage sciter -dynimport "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_.o" -dynout "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_import.go"
cd $WORK
gcc -no-pie -c trivial.c
gcc -nopie -c trivial.c
cd C:\Go\gopath\src\github.com\twelveandone\go
gcc -I "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306=/tmp/go-build" -gno-record-gcc-switches -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_all.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_export.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter_windows.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\types.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\utils.cgo2.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\callbacks.o" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter-x-api.o" -g -O2 -Wl,-r -nostdlib
"C:\\Go\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go.a" -trimpath "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306" -goversion go1.9 -p github.com/twelveandone/go -buildid 3a18df47f9a26d5215f3cbe24970d0b1dd2b4b25 -D _/C_/Go/gopath/src/github.com/twelveandone/go -I "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306" -I "C:\\Go\\gopath\\pkg\\windows_amd64" -pack "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\generate.go" "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\types_string.go" "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\value.go" "C:\\Go\\gopath\\src\\github.com\\twelveandone\\go\\wrapper.go" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_gotypes.go" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter.cgo1.go" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\sciter_windows.cgo1.go" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\types.cgo1.go" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\utils.cgo1.go" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_cgo_import.go"
pack r "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go.a" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-build623023306\\github.com\\twelveandone\\go\\_obj\\_all.o" # internal
mkdir -p C:\Go\gopath\pkg\windows_amd64\github.com\twelveandone\
mv $WORK\github.com\twelveandone\go.a C:\Go\gopath\pkg\windows_amd64\github.com\twelveandone\go.a

**Comment by twelveandone** [comment]
can work  Thanks

**Comment by pravic** [comment]
Closing in favor of #136.
