### ISSUE TITLE
A Problem about "sample-glassy-window.htm"

### ISSUE THREAD

**Issue by ying911008** [sciter-sdk/go-sciter#138]
I see an example in sciter-sdk which name is "sample-glassy-window.htm", And I write it width golang, it can't get work well, but run the *.html in sciter.exe, it can work well, why?
Here's my code:

#Html

```
<html window-frame="default" window-blurbehind>
<head>
  <title>Glassy window</title>
  <style>
    html 
    { 
      font:system;
      background:transparent; 
      overflow:none;
      padding:0;
    }
    
  </style>
</head>
<body>
MyTest
</body>
</html>

```

#Go 

```
package main

import (
	"log"
	"github.com/sciter-sdk/go-sciter"
	"github.com/sciter-sdk/go-sciter/window"
)


func main() {
	rect := sciter.NewRect(0, 0, 500, 350)
	// create window
	w, err := window.New(sciter.DefaultWindowCreateFlag, rect)
	if err != nil {
		log.Fatal(err)
	}

	w.LoadFile("my-glassy.html")
	w.SetTitle("MyClassy")

	w.Show()
	w.Run()
}
```

![20180424191133](https://user-images.githubusercontent.com/9350416/39183910-2bfc23b6-47f4-11e8-9a24-8e8c1821c972.png)

**Comment by pravic** [comment]
Windows 10? It requires a compatibility manifest:

https://github.com/c-smile/sciter-sdk/blob/1f6f9afc6bf3c4f60ea510fc75f89634f282d15d/demos/sciter/res/dpi-aware.manifest#L9-L22

**Comment by ying911008** [comment]
Yes, It do it in Windows 10,but when  I add a compatibility manifest, here‘s an error:

```
C:\Users\ZYQ\go\src\Glassy>rsrc -manifest my-glassy.manifest -o rsrc.syso


C:\Users\ZYQ\go\src\Glassy>set CGO_ENABLED=0

C:\Users\ZYQ\go\src\Glassy>set GOOS=windows

C:\Users\ZYQ\go\src\Glassy>set GOARCH=386

C:\Users\ZYQ\go\src\Glassy>go build -ldflags="-H windowsgui"
# github.com/sciter-sdk/go-sciter
..\github.com\sciter-sdk\go-sciter\types_string.go:27:9: undefined: BehaviorEvent
```

**Comment by ying911008** [comment]
OK, I see it in https://github.com/sciter-sdk/go-sciter/issues/130, I've solved it.

**Comment by pravic** [comment]
Shall I close this one then?
