### ISSUE TITLE
windows_amd64 build failed 

### ISSUE THREAD

**Issue by waleson** [sciter-sdk/go-sciter#140]
//////////////
>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\gopath\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\waleson\AppData\Local\Temp\go-build601292191=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

>gcc --version
gcc (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

///////////////////////////////
>go version
go version go1.9 windows/amd64

////////////////////////
> go build

# _/D_/Applications/scui
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
E:/tools/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\waleson\AppData\Local\Temp\go-link-205214491\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status

**Comment by waleson** [comment]
thank you,

may be ,I will update my go version to V1.10  with x86

**Comment by pravic** [comment]
No, better use Go 1.10 amd64 with mingw64 x64.

Or Go x86 with mingw i686.

Tested on these versions: https://github.com/sciter-sdk/go-sciter/blob/5e53faa0934384df3cd32ffaeb0f82788a5093b9/.appveyor.yml#L13-L23

**Comment by pravic** [comment]
Closing in favor of #136.
