### ISSUE TITLE
crash on winxp

### ISSUE THREAD

**Issue by zsdevX** [sciter-sdk/go-sciter#145]
winxp 32

```
[33mWARN[0m[0000] Opening UI
Exception 0xc0000005 0x0 0x54 0x33868627
PC=0x33868627
signal arrived during external code execution
syscall.Syscall(0x77d2aeab, 0x1, 0xc0132, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/runtime/syscall_windows.go:171 +0xcf
github.com/lxn/win.UpdateWindow(0xc0132, 0x5)
        xxx/src/src/github.com/lxn/win/user32.go:2887+0x43
github.com/sciter-sdk/go-sciter/window.(*Window).Show(0x114f4720)
        xxx/src/src/github.com/sciter-sdk/go-sciter/window/window_windows.go:43 +0x3d

```

**Comment by zsdevX** [comment]
forget it, i run xp in virtualbox, maybe not the sciter problem.

**Comment by zsdevX** [comment]
Sciter apps  from sciter-sdk  are crash too.

MY app compiled in WIN7 with mysys2 with goarch 386.

i see the crash in ```lnx/win```, and i'am sure it support winxp， but not sure if it can crash in virtualbox。well i will try now。

**Comment by zsdevX** [comment]
i checked lxn/win example, it works fine in virtualbox. :(

**Comment by pravic** [comment]
> Sciter apps from sciter-sdk are crash too.

That's the problem then. As far as I know, Sciter still does support Windows XP, so file an issue in https://sciter.com/forums/forum/bug-reports/ section.
