### ISSUE TITLE
Slow scrolling (vertically) in window with content

### ISSUE THREAD

**Issue by gcstang** [sciter-sdk/go-sciter#147]
Is there any reason that scrolling would be really slow?

Something I might be able to modify?

Mac Platform

Go 1.10.2

**Comment by pravic** [comment]
If [this](https://github.com/sciter-sdk/go-sciter/blob/d869f5fb60824aaeb0f5ca6d381c39bc75abbebc/types.go#L1185) won't help, ask on http://sciter.com/forums
