### ISSUE TITLE
sciter.Value.Int64 always return 0.

### ISSUE THREAD

**Issue by AllenDang** [sciter-sdk/go-sciter#148]
Here is the code:
`w.DefineFunction("getChapters", func(args ...*sciter.Value) *sciter.Value {`
`    fmt.Println(args, args[0].Int(), args[0].Int64())`

The output is:
[8] 8 0

**Comment by pravic** [comment]
TIScript [does not have](https://sciter.com/docs/content/script/language/Types.htm) 64-bit integers. 32-bit and less integers stored as int32 (`T_INT`), 64-bit integers have to be stored as double float (`T_FLOAT`).

`Int64`/`SetInt64` are misleading and, in fact, their purpose is to store 64-bit integer data of `T_CURRENCY` and `T_DATE` values.

So, unless your script returns Date or Currency, `Int64` will return `0` (but it should return `error` instead).

N.B that TIScript is a static typing language and values are not implicitly converted (unlike in JavaScript).

**Comment by AllenDang** [comment]
Thanks for your answer.
