### ISSUE TITLE
How to show a modal child window?

### ISSUE THREAD

**Issue by AllenDang** [sciter-sdk/go-sciter#149]
I have a main window running, how to show a modal child window from go side?

I know tiscript could easily implement it, but I want to use go code to define functions for frontend script to do the data IO.

I tried to create a new window the SW_CHILD, but nothing happened when I call show() and run().

**Comment by pravic** [comment]
Modal means dialog. SW_CHILD is about child windows (i.e embedded like a button or a textbox in the window).

What you need is a modal dialog which [owner](https://social.msdn.microsoft.com/Forums/vstudio/en-US/a074fad6-b9c0-49de-a35c-0ad3c876485a/whats-the-difference-between-parent-window-ancestor-and-owner-window?forum=vcgeneral)
will be your window.

But as far as I know, you can't create a dialog with SciterAPI. However, you can create a native dialog and attach Sciter to it.

**Comment by pravic** [comment]
I think it's much easier to use `view.dialog`. Don't forget that you can call it from the native side as well.

**Comment by AllenDang** [comment]
Hah, let me take a look at window.Call. Will get back to you soon

**Comment by AllenDang** [comment]
En, I don't think to call `view.dialog` could solve my problem...

I need to call go function from the dialog's script.

Any thought?

**Comment by AllenDang** [comment]
Ok, I solved it. 

1. Define the go functions at main window.
2. Call `view.dialog("abc.html", view);` from tiscript.
3. In the dialog's script, use `view.parameters.method()` to call the go function.

**Comment by pravic** [comment]
That's what I wanted to tell you, too.
