### ISSUE TITLE
Some strange error

### ISSUE THREAD

**Issue by seuviceversa** [sciter-sdk/go-sciter#151]
# github.com/sciter-sdk/go-sciter
..\github.com\sciter-sdk\go-sciter\sciter.go:703: cannot use bs (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString
..\github.com\sciter-sdk\go-sciter\sciter.go:832: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\sciter.go:849: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\sciter.go:911: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\sciter.go:923: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\types.go:596: cannot use s.name (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString
..\github.com\sciter-sdk\go-sciter\types.go:972: cannot use s.behaviorName (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString

Compilation finished with exit code 2

My code is:
package main
 
import (
    "github.com/sciter-sdk/go-sciter"
    "github.com/sciter-sdk/go-sciter/window"
    "log"
)
 
func main() {
    w, err := window.New(sciter.SW_TITLEBAR|
        sciter.SW_RESIZEABLE|
        sciter.SW_CONTROLS|
        sciter.SW_MAIN|
        sciter.SW_ENABLE_DEBUG,
        nil);
    if err != nil {
        log.Fatal(err);
    }
    w.LoadFile("demo1.html");
    w.SetTitle("HW");
    w.Show();
    w.Run();
}

I have finished and checked the 'Getting Started'.

**Comment by pravic** [comment]
Go and gcc versions?

**Comment by tyharg** [comment]
+1 on this issue.

`
[tyler@localhost go-sciter]$ go version
go version go1.9.4 linux/amd64
[tyler@localhost go-sciter]$ gcc --version
gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`

**Comment by pravic** [comment]
Thanks! It's #136.
