### ISSUE TITLE
Async in tiscript doesn't work.

### ISSUE THREAD

**Issue by AllenDang** [sciter-sdk/go-sciter#153]
My code is below

```
async function someLongOp() {
  $(#btnGo).state.disabled = true;

  var result = await longOp();

  $(#btnGo).state.disabled = false;
} 

self.post(function() {
  $(#btnGo).on("click", function() {
    someLongOp();
  })
})
```

It suppose to be a async call, but the main thread is blocked. Am I using await in the right way?

**Comment by pravic** [comment]
Such things better ask on sciter.com

**Comment by pravic** [comment]
https://github.com/c-smile/sciter-sdk/issues/83

Wait, you are stating that it does not work only with Go.

Than it belongs here.

**Comment by AllenDang** [comment]
I actually filed another issue here...

**Comment by pravic** [comment]
> Than it belongs here.

Nah, it doesn't. You just doing it wrong.

First of all, documentation:

* https://sciter.com/docs/content/script/language/Statements.htm (`await`)
* https://sciter.com/promisesa-implementation-in-sciter2/ (apparently, there is no online equivalent of the sciter-sdk/doc/content/script/language/promise.htm)
* sciter-sdk/samples/+promise/readme.htm

The `await` operator works with `promise`s and only with `promise`s while a `view.NativeFunction` isn't a promise, of course.

To make your code work use the following:

```javascript

      async function asyncNative(self) {
        // create a `promise` object with our own callback
        var p = promise(function(resolve, reject) {
          debug: "promise start";
          try {

            // call our native function here
            var res = view.native_func();

            debug: "promise ready";

            // and pass the result back to the `await` waiter
            resolve(res);
          }
          catch(e) {
            debug alert: "promise error" e.message e.data;

            // catch an error and pass it to the `await` caller
            reject(e);
          }

          // nothing to se here, really
          debug: "promise end";
        });

        debug: "request";

        // the following is wrong since our native function aren't promises-like objects:
        // var res = await view.asyncNative();

        // use this instead:
        var res = await p;

        // fullfill the UI:
        debug: "result" res;
        $(output).value = res;

        // and finally restore the button's state back:
        self.state.disabled = false;
      }
```

And call it:

```javascript

      $(#nativeasync) << event click {

        // prepare the UI
        this.state.disabled = true;

        // call our async function
        asyncNative(this);

        // the following is wrong because 
        // an async function returns **immediately**;
        // use callback instead
        // this.state.disabled = false;
      }

```

**Comment by AllenDang** [comment]
You really save my life here!

**Comment by AllenDang** [comment]
No, it still doesn't work...

go side

```
func sleep() {
  time.Sleep(time.Second * 4)
}
```

tiscript side

```
async function asyncSleep(folder, output) {
    var p = promise(function(resolve, reject) {
        try {
            var res = view.sleep();
            resolve(res);
        } catch(e) {
            reject(e);
        }
    });

    $(#btnGo).state.disabled = true;

    var result = await p;

    $(#btnGo).state.disabled = false;
}
```

When I call asyncSleep() the main thread still be blocked.

**Comment by pravic** [comment]
Also it can be simplified to:

```javascript
async function asyncNative() {
  var p = promise(function (on_ok, on_fail) {
    view.async_func(on_ok, on_fail);
  });
  return await p;
}
```

```go
w.defineFunction("async_func", func(args... *sciter.Value) *sciter.Value {
  on_ok := args[0]
  on_fail := args[1]

  // in form of `script.Invoke(this, "stacktrace", args...)`
  on_ok.Invoke(sciter.NullValue(), "[async_func]", sciter.NewValue("OK"))
})

```

**Comment by pravic** [comment]
> When I call asyncSleep() the main thread still be blocked.

What do you mean by "main thread"?

**Comment by AllenDang** [comment]
UI is not responding.

**Comment by pravic** [comment]
How about doing blocking operations in a goroutine and calling promise when done?

**Comment by AllenDang** [comment]
I thought about using goroutine and callback when it's done. Side effect is this breaks the async/await pattern sciter has.

**Comment by pravic** [comment]
Why does this break the pattern?

```javascript
async function asyncNative() {
  var p = promise();
  view.set_promise(p);

  // await
  var res = await p;

  // use result
  $(output).value = String.printf("ok: %V", res);
}
```

```python
    @sciter.script(convert=False)
    def set_promise(self, oath):

        def thread_func(oath):
            import time
            time.sleep(2)
            oath(True, ["OK"])

        import threading
        t = threading.Thread(target=thread_func, args=(oath,))
        t.start()
    pass
```

It is in Python but you've got the point: I create a `promise`, pass it to the native code which creates a new thread and does some sleepy work. Eventually the promise is fulfilled by result.

Note array in `oath(True, params)` because (from [the docs](https://github.com/c-smile/sciter-sdk/blob/master/samples/%2Bpromise/readme.htm)):

> call it as `prom(true, params)`. Where the params is an array of values that will be applied to `onFulfilled` callback functions registered by `.then()` method.

**Comment by AllenDang** [comment]
En, you got the point. I think you are right.

**Comment by AllenDang** [comment]
It seems I cannot invoke the promise object at go side.

tiscript

```
var p = promise();
view.longOp(p);
var result = await p;
```

go side

```
func waitHere(p *sciter.Value) {
  time.Sleep(time.Second * 5)
  p.Invoke(sciter.NullValue(), "[native func wait]", sciter.NewValue(true), sciter.NewValue())
}

func longOp(...) {
  promise := args[0]
  go waitHere()
}
```

Turns out promise in go side is not a function. Error message is HV_INCOMPATIBLE_TYPE: ValueInvoke.

I think I'm very close the solution.... What I do wrong here?

**Comment by pravic** [comment]
Well, it was tricky.

The problem was in a premature optimization in a way how go-sciter deals with scripting arguments. They are pointers (not values), that's why you have garbage in goroutine instead of promise.

Workaround (until I fix it) would be the following:

```go
func longOp(...) {
  promise := args[0] // `promise` here just a pointer
  go waitHere(promise.Clone()) // make a real Value from it
}
```

**Comment by AllenDang** [comment]
Aha! The workaround works. I will use it now and looking forward to your fix. :)

**Comment by pravic** [comment]
> apparently, there is no online equivalent of the sciter-sdk/doc/content/script/language/promise.htm

I've just found it: https://sciter.com/docs/content/sciter/promise.htm
It is inside the [DOM classes](https://sciter.com/developers/sciter-docs/dom-classes/) section unlike in offline docs where it is suited in Sciter Script's section.

**Comment by jqqjj** [comment]
I have the same problem. Could you show your full example codes? @AllenDang 

My problem is here. #254 

Thanks.
