### ISSUE TITLE
Async function in tiscript doesn't work with go function.

### ISSUE THREAD

**Issue by AllenDang** [sciter-sdk/go-sciter#154]
async and await works fine with pure tiscript function, like below

```
async function getRemoteTextTask(url) 
{
    var text = await view.request { url: url, output: #string };
    $(#btnGo).text = text;
}
```

But when await followed by a function defined at go side, the async will not work any more.

```
async function getRemoteTextTask(url) 
{
    var text = await view.gofunction();
    $(#btnGo).text = text;
}
```

**Comment by pravic** [comment]
No, if you are not agree with issue closing, just continue to post in there rather than creating a new one.
