### ISSUE TITLE
cannot compile with go1.10

### ISSUE THREAD

**Issue by 756445638** [sciter-sdk/go-sciter#156]
cannot compile with go1.10
cannot compile with go1.10
cannot compile with go1.10

**Comment by 756445638** [comment]
$ go version
go version go1.10.1 windows/amd64

$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\golib;D:\backstage\newest\hmi-server\code\gopath
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build339755350=/tmp/go-build -gno-record-gcc-switches
$ go run /d/backstage/newest/hmi-server/code/gopath/src/hmi-server/healthcheck/main.go
# github.com/sciter-sdk/go-sciter
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:119: invalid indirect of _Ctype_uchar(unsafe.Pointer(&data[0])) (type _Ctype_uchar)
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:119: cannot convert unsafe.Pointer(&data[0]) (type unsafe.Pointer) to type _Ctype_uchar
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:235: invalid indirect of _Ctype_uchar(unsafe.Pointer(StringToBytePtr(data))) (type _Ctype_uchar)
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:235: cannot convert unsafe.Pointer(StringToBytePtr(data)) (type unsafe.Pointer) to type _Ctype_uchar
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:253: invalid indirect of _Ctype_uchar(unsafe.Pointer(StringToBytePtr(data))) (type _Ctype_uchar)
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:253: cannot convert unsafe.Pointer(StringToBytePtr(data)) (type unsafe.Pointer) to type _Ctype_uchar
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:273: invalid indirect of _Ctype_uchar(unsafe.Pointer(StringToBytePtr(css))) (type _Ctype_uchar)
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:273: cannot convert unsafe.Pointer(StringToBytePtr(css)) (type unsafe.Pointer) to type _Ctype_uchar
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:733: invalid indirect of _Ctype_uint(&count) (type _Ctype_uint)
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:733: cannot convert &count (type *_Ctype_uint) to type _Ctype_uint
D:\golib\src\github.com\sciter-sdk\go-sciter\sciter.go:733: too many errors

there should be enough for you , thanks ...

**Comment by pravic** [comment]
Yes, it is helpful. Could you tell me your GCC version?

**Comment by 756445638** [comment]
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\TDM-GCC-64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)

**Comment by 756445638** [comment]
Is this cause by gcc??

**Comment by pravic** [comment]
Yes, you need 6.x gcc version.

**Comment by pravic** [comment]
Feel free to ask if something pops up.
