### ISSUE TITLE
default callback handler that resolve files archived using packfolder

### ISSUE THREAD

**Issue by mchampaneri** [sciter-sdk/go-sciter#163]
There should be a defaultCallBackHandler function that resolves files from archive.

**Function**
```
func (sc *Sciter) DefaultCallBackHandler() {
	callback := &CallbackHandler{
		OnLoadData: func(params *ScnLoadData) int {
			if strings.HasPrefix(params.Uri(), "file://") {
				fileData := sc.GetArchiveItem(params.Uri()[7:])
				sc.DataReady(params.Uri()[7:], fileData)
			}
			return 0
		},
	}
	sc.SetCallback(callback)
}
```
**Useage**

```
func main() {
	
	rect := sciter.NewRect(100, 100, 300, 500)	
	win, _ := window.New(sciter.SW_MAIN|sciter.SW_CONTROLS|sciter.SW_ENABLE_DEBUG, rect)
 
	win.DefaultCallBackHandler() //  Will resolved file path during OnLoadData event
	win.OpenArchive(resources)

	htbytes := win.GetArchiveItem("notepad.htm")
	win.LoadHtml(string(htbytes), "")
	win.SetTitle("Demo")

	win.Show()
	win.Run()

	win.CloseArchive()
}

```

**Comment by pravic** [comment]
I think, this can be improved:

```go
  // win.DefaultCallBackHandler()
  // win.OpenArchive(resources)

  // usage:
  win.SetResourceArchive(resources)
  win.LoadFile("this://app//notepad.htm")

  // win.SetTitle("Demo") - there is no point in this call if notepad.htm contains <title>
```

```go
// in library
func (sc *Sciter) SetResourceArchive(data []byte) {
  sc.OpenArchive(data)
  sc.SetCallback(...)
}
```

**Comment by mchampaneri** [comment]
@pravic 

> So you need to change only URL of the main file.

Actully , Its not working for me. When i just loaded main.html, It was not able to find style.css file. I have to load every file from archive on their url using  **sc.DataReady(url, file-bytes)**

**Comment by pravic** [comment]
Again, to make it work you need to load the main html using an absolute url. Either via `LoadHtml` or `LoadFile`. Or show your code, I might miss something.

**Comment by mchampaneri** [comment]
@pravic 

I have uploaded zip file containing code.

It contains 4 resource files, 2 go files and packfolder.exe 
- notepad.htm
- style.css
- abc.html
- new_style.html
- main.go
- res.go [ generated using packfolder.exe ]

During Callback function I have to load css file to their relative url using 
```
	win.GetArchiveItem(params.Uri()[7:])
	win.DataReady(params.Uri()[7:], fileData)
```

Otherwise css files are not get found,

Callback function loads the files according to the html file I am loading from archive using GetArchiveItem

[08-packfolderIntro.zip](https://github.com/sciter-sdk/go-sciter/files/2248187/08-packfolderIntro.zip)

**Comment by pravic** [comment]
25d8ed4 contains `SetResourceArchive` and a usage example (`examples/restest2`).

**Comment by mchampaneri** [comment]
@pravic 

I am getting still same problem. Css is not loading.

// Output I am getting

![image](https://user-images.githubusercontent.com/13694774/43512127-e1fa79ba-9597-11e8-933f-16e27a500099.png)

// Expcted Output
![image](https://user-images.githubusercontent.com/13694774/43512212-142e6004-9598-11e8-8c96-3c0abf06bf86.png)

**Please can you send me  sample. or highlight changes you have done in the sample i have sent to you**

**Comment by pravic** [comment]
Okay than. Thanks for bringing this up.
