### ISSUE TITLE
不使用tiscript，使用go代码，可否动态更新html元素

### ISSUE THREAD

**Issue by bishen** [sciter-sdk/go-sciter#164]
func main() {
	w, err := window.New(sciter.SW_TITLEBAR|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN|sciter.SW_ENABLE_DEBUG, nil)
	if err != nil {
		log.Fatal(err)
	}
	// log.Printf("handle: %v", w.Handle)
	w.LoadFile("1.html")
	w.SetTitle("test")

	root, err := w.GetRootElement()
	if err != nil {
		log.Panicln(err)
	}
  w.Show()
	w.Run()
  // 已经运行了，
  // 后面可否在动态更新 html node
	el, _ := root.SelectById("gradient-rotated")
	el.SetText("00000000")
	w.UpdateWindow()  // 无用
	w.Show()
	w.Run()
}

**Comment by pravic** [comment]
Could you translate to English?

**Comment by maojindao55** [comment]
@bishen 解决了吗？
