### ISSUE TITLE
Add a release tag to support go modules

### ISSUE THREAD

**Issue by tekjar** [sciter-sdk/go-sciter#166]
Pretty much the title

**Comment by pravic** [comment]
Does Go have modules now?

Also what I'm supposed to use as a tag? As far as I know, Go does not version packages.

**Comment by tekjar** [comment]
https://github.com/golang/go/wiki/Modules

Added very recently I guess. Tag should be semantic versioned prefixed with 'v' e.g v1.2.3

**Comment by tekjar** [comment]
Don't know complete details. I mostly use rust. Still deciding on go-sciter or rust-sciter :).

**Comment by pravic** [comment]
> Still deciding on go-sciter or rust-sciter

The latter is better documented (J.)

**Comment by pravic** [comment]
https://github.com/sciter-sdk/go-sciter/releases/tag/v0.5.0

Haven't checked how it works either. But I hope it helps.

**Comment by tekjar** [comment]
Works. Thanks
