### ISSUE TITLE
running example have an error.

### ISSUE THREAD

**Issue by yanyuxuanz** [sciter-sdk/go-sciter#167]
..\github.com\sciter-sdk\go-sciter\sciter.go:742: cannot use bs (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString
..\github.com\sciter-sdk\go-sciter\sciter.go:871: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\sciter.go:888: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\sciter.go:950: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\sciter.go:962: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
..\github.com\sciter-sdk\go-sciter\types.go:596: cannot use s.name (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString
..\github.com\sciter-sdk\go-sciter\types.go:972: cannot use s.behaviorName (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString

**Comment by pravic** [comment]
Go and mingw versions?

**Comment by yanyuxuanz** [comment]
go version is 1.9.3,and tdm64-gcc-5.1.0-2,now I cmd go get github.com/sciter-sdk/go-sciter.The same problem has arisen

**Comment by yanyuxuanz** [comment]
$ go get github.com/sciter-sdk/go-sciter
# github.com/sciter-sdk/go-sciter
sciter-sdk\go-sciter\sciter.go:742: cannot use bs (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString
sciter-sdk\go-sciter\sciter.go:871: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
sciter-sdk\go-sciter\sciter.go:888: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
sciter-sdk\go-sciter\sciter.go:950: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
sciter-sdk\go-sciter\sciter.go:962: cannot use cname (type *C.char) as type *C.CHAR in argument to func literal
sciter-sdk\go-sciter\types.go:596: cannot use s.name (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString
sciter-sdk\go-sciter\types.go:972: cannot use s.behaviorName (type C.LPCSTR) as type *C.char in argument to _Cfunc_GoString

**Comment by pravic** [comment]
Unfortunately, #136 is your case.

**Comment by pravic** [comment]
Closing this in favor of that issue.

**Comment by yanyuxuanz** [comment]
OK.all right.thanks and I  didn't pay attention to that tag.you mean only the 1.9 version is ok?the latest or since 1.9 version unsupport?

**Comment by pravic** [comment]
I've made it more clear, I hope: https://github.com/sciter-sdk/go-sciter/releases 

[`go-1.9`](https://github.com/sciter-sdk/go-sciter/releases/tag/go-1.9) is for Go 1.9 or lower, `master` or any other release is for Go 1.10 or higher (we have 1.11 now).

**Comment by yanyuxuanz** [comment]
I got package of that version. and running no error,thanks very much.
