### ISSUE TITLE
Create new window  can not control by handle for Go,

### ISSUE THREAD

**Issue by yanyuxuanz** [sciter-sdk/go-sciter#170]
if I use tiscript to create a new window,then I can't use "view" Object to call  go's EventHandler window.DefineFunction();Perhaps I don't know which I  have a mistake..
In other words,the main go can only provide handlers for the main window.

**Comment by pravic** [comment]
You can make a proxy object with required functions and pass it to the newly created window:

Main window:

```javascript

var API = {
  msgBox: function(args..) { view.msgbox.apply(view, args); },
  nativeCall: function(args..) { view.nativeCall.apply(view, args); },
};

view.window( { 
  type: View.POPUP_WINDOW,
  url: ...,

  parameters: API,  // <-- pass our API to a new window
});
```

New window:

```javascript
var API = view.parameters;
API.msgBox(#information, "Hello");
```

**Comment by pravic** [comment]
Also https://sciter.com/forums/topic/how-to-call-the-native-function-from-the-dialog-view/

**Comment by yanyuxuanz** [comment]
aha,Solved the problem, same as you said.Thanks.
