### ISSUE TITLE
two beginners questions

### ISSUE THREAD

**Issue by coolit** [sciter-sdk/go-sciter#171]
01- Some of the html files in examples cannot be opened in sciter.exe. I was wondering what tool is used to produce such html files?
02- When loading sciter-sdk\samples\ideas\grid.htm in golang, the top buttons doesn't work, and fonts are not clear. 

I'm using win10 amd64.
Thanks.

**Comment by coolit** [comment]
e.g. "examples\demoes\01\demo1.html" couldn't be opened by sciter-sdk\bin\64\sciter.exe
Actually many of them couldn't be opened, but all examples under sdk could be properly opened.

**Comment by coolit** [comment]
For question 02, you are right, I missed some path relation there.

**Comment by pravic** [comment]
Also what did you mean by "couldn't be opened by sciter"?

I just checked, it works as expected. In fact, there is nothing much to "open" in there, just a hello world:

https://github.com/sciter-sdk/go-sciter/blob/25d8ed42e0bb4c4acb742de9f148f6902d32ff41/examples/demoes/01/demo1.html#L1-L9

![demo1](https://user-images.githubusercontent.com/724639/45925124-5a4e4780-bf18-11e8-91ad-00597bf32dfe.png)

**Comment by coolit** [comment]
In my case, it works after I changing .html to .htm.

**Comment by pravic** [comment]
Magic.
