### ISSUE TITLE
how to use SetState

### ISSUE THREAD

**Issue by coolit** [sciter-sdk/go-sciter#172]
What does `bitsToClear` in SetState function mean exactly? May I use `0`? 
```
row.SetState(sciter.STATE_CURRENT, 0, true)
```

**Comment by pravic** [comment]
For example, to expand some panel you would clear the STATE_COLLAPSED and set a STATE_EXPANDED.
Or just to clear something previously set. Yes, you can use `0` if you have nothing to reset in an element.

**Comment by coolit** [comment]
Thanks.

**Comment by pravic** [comment]
`STATE_CURRENT` can be a tricky though, better ask on sciter.com/forums.
