### ISSUE TITLE
Not using C.CString in Sciter.Call causing null termination to be removed in some cases

### ISSUE THREAD

**Issue by CodingBeard** [sciter-sdk/go-sciter#183]
https://github.com/sciter-sdk/go-sciter/blob/master/sciter.go#L360

`cfn := C.LPCSTR(unsafe.Pointer(StringToBytePtr(functionName)))`

Sometimes doesn't correctly null terminate and causes the function name to continue reading from memory till it finds a null terminator

E.G.  with a `w.Call("$(frame#main-container)[0].ns.Main.ConnectionButton.disconnected", sciter.NullValue())`
![screen shot 2018-11-01 at 14 11 26](https://user-images.githubusercontent.com/4483620/47856902-37993380-dde0-11e8-9ae5-76cb99d0fec1.png)

Replacing the line with:

`
funcName := C.CString(functionName);
defer C.free(unsafe.Pointer(funcName));
cfn := C.LPCSTR(unsafe.Pointer(funcName));
`

Resolves the issue.

Thanks

**Comment by pravic** [comment]
Thanks for the catch! I'll fix it soon, or you can send a PR.
