### ISSUE TITLE
how to close the main window

### ISSUE THREAD

**Issue by TerryMarszr0** [sciter-sdk/go-sciter#184]
how to close the main window

**Comment by pravic** [comment]
By pressing the [X] button? Your question is a bit ambiguous.

**Comment by TerryMarszr0** [comment]
i want to delay to destory the main window ,code as below ,but it looks like cant destory main window or break main window
	go func() {
		time.Sleep(30 * time.Second)
		//hwnd := appWindow.GetHwnd()
		hwdn := win.HWND(unsafe.Pointer(appWindow.GetHwnd()))
		win.SendMessage(hwdn, win.WM_CLOSE, 0, 0)
		//win.DestroyWindow(hwdn)

	}()

**Comment by pravic** [comment]
You can't sleep in UI thread (and goroutine does not guarantee you that it will be run in a separate thread).  Use timers. 

TIScript:
```javascript
self.timer(30*1000, function() { view.close(); });
```

**Comment by TerryMarszr0** [comment]
thanks
