### ISSUE TITLE
demo9中的bug问题

### ISSUE THREAD

**Issue by nickHsiung** [sciter-sdk/go-sciter#187]
![image](https://user-images.githubusercontent.com/12226481/50465435-4f50fa80-09d2-11e9-811a-df6213cc172e.png)
-----------
#### 系统：
![image](https://user-images.githubusercontent.com/12226481/50465486-a9ea5680-09d2-11e9-9800-1aa7eae47cf5.png)
--------
#### 遇到问题：
1.点击 选择文件没有反应
2.点击 窗口 打开新窗口没有显示simple.html里边的内容
3.点击 请求 没有任何反应
----
1.can't open FileDialog
2. open new window can't load simple.html info.
3. network is not working.

---
. 问题 2 的表现
![image](https://user-images.githubusercontent.com/12226481/50465601-267d3500-09d3-11e9-88f2-90f84cb15a3c.png)

. 问题3表现

**Comment by nickHsiung** [comment]
![image](https://user-images.githubusercontent.com/12226481/50466054-32b6c180-09d6-11e9-9922-83c89c4b0c0c.png)

**Comment by pravic** [comment]
Hello. Is there any chance to write this in English?

**Comment by wiwii** [comment]
he said that "get" request method is not working.

**Comment by nickHsiung** [comment]
> Hello. Is there any chance to write this in English?

1.can open FileDialog
2. open new window can load simple.html info.
3. network is not working.
-----
Above questions from sciter-sdk/go-sciter/demo9 . My english so bad, Please reply me.thank you  so much.

**Comment by c-smile** [comment]
By default and for security reasons all communication and system probing functions accessible from script are disabled in Sciter.
So you should have something like this call before using any other Sciter API:
```
 SciterSetOption(NULL, SCITER_SET_SCRIPT_RUNTIME_FEATURES,
    ALLOW_FILE_IO |
    ALLOW_SOCKET_IO |
    ALLOW_EVAL |
    ALLOW_SYSINFO);
```
ALLOW_SOCKET_IO will enable network communication.

In Go:
```
sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SOCKET_IO)
```

**Comment by nickHsiung** [comment]
> By default and for security reasons all communication and system probing functions accessible from script are disabled in Sciter.
> So you should have something like this call before using any other Sciter API:
> 
> ```
>  SciterSetOption(NULL, SCITER_SET_SCRIPT_RUNTIME_FEATURES,
>     ALLOW_FILE_IO |
>     ALLOW_SOCKET_IO |
>     ALLOW_EVAL |
>     ALLOW_SYSINFO);
> ```
> ALLOW_SOCKET_IO will enable network communication.
> 
> In Go:
> 
> ```
> sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SOCKET_IO)
> ```

thank you sir.
