### ISSUE TITLE
Returnig array of data to sciter 

### ISSUE THREAD

**Issue by mchampaneri** [sciter-sdk/go-sciter#191]
#Is it possible to return array of elements to sciter  somthing like this 

`func returnlist(input ...*sciter.Value) (thubmUrls []*sciter.Value) `

**Comment by pravic** [comment]
I believe, you want something like this:

```go
func returnlist(input ...*sciter.Value) *sciter.Value {
  array := sciter.NewValue();
  for i := 0; i < 3; i++ {
    array.Append("item");
  }
  return array;
}

```javascript
var array = view.returnlist();
stdout.printf("array: %V\n", array);
```

**Comment by mchampaneri** [comment]
I was looking for same.

Thank you @pravic

**Comment by ShrinathGupta** [comment]
> I believe, you want something like this:
> 
> ```go
> func returnlist(input ...*sciter.Value) *sciter.Value {
>   array := sciter.NewValue();
>   for i := 0; i < 3; i++ {
>     array.Append("item");
>   }
>   return array;
> }
> ```
> 
> ```js
> var array = view.returnlist();
> stdout.printf("array: %V\n", array);
> ```

How can i create object of map from sciter? I want to store data in key and value format.

**Comment by pravic** [comment]
@ShrinathGupta Could you tell us more information?

**Comment by ShrinathGupta** [comment]
@pravic Assume i have to return map to the view. 

Example: 
```
data := map[string]string{
		"a": "ABC",
		"b": "BCD",
		"c": "CDE",
	}
```
How can i do that ? Ho can i create sciter collection object to return from function?

**Comment by pravic** [comment]
```go
data := sciter.NewValue()
data.SetItem("a", "ABC") 
```

Check sciter.Value's methods.
