### ISSUE TITLE
Some functions do not work for Sciter version 4.2.7.1

### ISSUE THREAD

**Issue by JerryKwan** [sciter-sdk/go-sciter#194]
When updating Sciter version to 4.2.7.1, seems like some functions break
For example:
1, System.path(#USER_DOCUMENTS); does not work anymore
2, view.selectFolder does not show the dialog anymore
Any suggestions about what caused the problem? And how to debug what's wrong? thank you

**Comment by pravic** [comment]
Check #180, #178. And [this](https://rawgit.com/c-smile/sciter-sdk/7036a9c7912ac30d9f369d9abb87b278d2d54c6d/logfile.htm).

**Comment by pravic** [comment]
I ought to put it somewhere, to be honest.

**Comment by JerryKwan** [comment]
@pravic , thank you for giving some references
The following code work
   sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_FILE_IO |
                    sciter.ALLOW_SOCKET_IO |
                    sciter.ALLOW_EVAL |
                    sciter.ALLOW_SYSINFO)
    // w, err := window.New(sciter.SW_TITLEBAR |
    //     sciter.SW_RESIZEABLE |
    //     sciter.SW_CONTROLS |
    //     sciter.SW_MAIN |
    //     sciter.ALLOW_SYSINFO |
    //     sciter.SW_ENABLE_DEBUG,
    //     &sciter.Rect{Left: 0, Top: 0, Right: 800, Bottom: 600})
    // SW_TITLEBAR | SW_RESIZEABLE | SW_CONTROLS | SW_MAIN | SW_ENABLE_DEBUG
    // w, err := window.New(sciter.SW_TITLEBAR|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN|sciter.ALLOW_SYSINFO,
    //     &sciter.Rect{Left: 0, Top: 0, Right: 800, Bottom: 600})
    // w, err := window.New(sciter.DefaultWindowCreateFlag, sciter.DefaultRect)
    w, err := window.New(sciter.SW_TITLEBAR |
        sciter.SW_RESIZEABLE |
        sciter.SW_CONTROLS |
        sciter.SW_MAIN |
        sciter.SW_ENABLE_DEBUG,
        &sciter.Rect{Left: 0, Top: 0, Right: 800, Bottom: 600})
Although view.selectFolder works, but why System.OS return wrong result?

**Comment by JerryKwan** [comment]
BTW, please do not use  sciter.ALLOW_SYSINFO when invoke window.New, seems like it will conflict with  sciter.SW_RESIZEABLE

**Comment by pravic** [comment]
Doesn't seem to be true. Could you forward the last message to sciter.com/forums?
