### ISSUE TITLE
How does textarea break through the limit of 10,000 words?

### ISSUE THREAD

**Issue by jiqi136** [sciter-sdk/go-sciter#195]
Whenever the number of words is about 10,000, the textarea cannot continue to be entered.
When maxlength = "90,000" is set, the window is not responding directly after too many words are input.

`<textarea id = "text1" rows = "50000" cols = "100"   maxlength = "number" > </ textarea> `

**Comment by pravic** [comment]
I believe, this should be filed at https://sciter.com/forums/forum/bug-reports/
