### ISSUE TITLE
LoadFile shall use absolute paths

### ISSUE THREAD

**Issue by c-smile** [sciter-sdk/go-sciter#199]
https://github.com/sciter-sdk/go-sciter/blob/e932564b0bc29be6eb2e49b00f31dc633258156c/examples/demoes/02/demo2.go#L30

In order the sample to work reliably, this:
```
w.LoadFile("demo2.html") 
```

shall use absolute path rather than relative (relative to what exactly?)

**Comment by oskca** [comment]
Yes, it should be
