### ISSUE TITLE
after selectFile function called and have selected file ,i can not wirte file in golang

### ISSUE THREAD

**Issue by subing** [sciter-sdk/go-sciter#20]
when i call selectFile function,after that when where i write file in golang,i can write file success in my log,return the number of writed,but no content has writed when i open the file which has writed.

**Comment by oskca** [comment]
Writing files is a golang operation, perhaps you should call `File.Close()` after the `File.Write`?

**Comment by subing** [comment]
thanks  for your answer,and i find the reason of which i can write file after call selectFile,i don't know is this a bug,that is selectFile will change my golang exec dir to  dir  i select file's

**Comment by pravic** [comment]
This behavior is default on Windows. As a workaround you can save and restore the current directory.
