### ISSUE TITLE
`w. LoadFile()` load utf-8 file

### ISSUE THREAD

**Issue by hechty** [sciter-sdk/go-sciter#213]
When I use `w. LoadFile ()`, if the file is encoded as `utf-8`, the Chinese language will be scrambled after loading, and the file code must be changed to `UTF-8 with BOM` to display Chinese normally.

How can i load utf-8 file?

**Comment by pravic** [comment]
Yes, Sciter requires BOM in loaded files. 

If you want to use files without BOM, you could load files in memory and insert the mark in run time.

**Comment by c-smile** [comment]
On Windows you should either add UTF-8 BOM to your files or advertise UTF-8 encoding  as:

```
<html>
   <head>
      <meta charset="UTF-8">
      ...   
```
