### ISSUE TITLE
setIcon function

### ISSUE THREAD

**Issue by coolit** [sciter-sdk/go-sciter#22]
Currently the output exe file is without any icon.
I used an icon changer to give it an icon, and as a result the taskbar and exe icons looked fine, but the top-left icon remained unchanged.
It would be great if this function is available.
Thanks.

**Comment by AlexDias79** [comment]
Hello, 
That's quite possible. Have a look at https://github.com/josephspurrier/goversioninfo

**Comment by midiway** [comment]
check how you can do it in SciterSharp: https://github.com/MISoftware/SciterSharp/blob/master/SciterSharp/SciterWindow.cs#L308

**Comment by pravic** [comment]
Since 3.3.2.13:

* `view.windowIcon = null | "url" | Image;` - set window icon programmatically. See: sciter-sdk/samples.dialogs+windows/window-icon.htm
* `<html window-icon="url">` html property for the same purpose.
