### ISSUE TITLE
LoadHtml

### ISSUE THREAD

**Issue by c-smile** [sciter-sdk/go-sciter#223]
https://github.com/sciter-sdk/go-sciter/blob/63639436cb8c6ae926e738b4ebc1b83df292d8ef/examples/simple/simple.go#L16

LoadFile must use absolute path.

**Comment by mrg0lden** [comment]
Do you mean it should only receive absolute paths or in this example it should be given an absolute path instead?

**Comment by c-smile** [comment]
```LoadFile(fileUrl)``` shall be given absolute URL or path.

Content of that file may use relative paths, for example 

```
<html>
   ....
   <img src="images/foo.png"> 
</html>
```
The image will be loaded from `{....fileUrl folder here}/images/foo.png`

That's exactly the same situation as in browsers. Open your browser and put "simple.html" in its address bar, will you have anything meaningless from it?

**Comment by mrg0lden** [comment]
Well, I think I get your point.
What if the Go side of the implementation checks if it's an absolute path, if not returns an error? (I can do this)
This however will break existing examples and programs that are tied to the current implementation. This can be held for a new version release, while updating the current examples as of now to adhere to the rule.

**Comment by c-smile** [comment]
> What if the Go side of the implementation checks if it's an absolute path

No. That's responsibility of your application.

This call:
```w.LoadFile("simple.html")``` 
makes perfect sense if you [handle SC_LOAD_DATA](https://github.com/sciter-sdk/go-sciter/blob/master/sciter.go#L194) and load "simple.html" from database for example.

**Comment by pravic** [comment]
All the examples

**Comment by pravic** [comment]
Seeing all the 

```go
	fullpath, err := filepath.Abs("simple.html")
	if err != nil {
		log.Fatal(err)
	}
	w.LoadFile(fullpath)
```

I was wondering why don't we simplify it?

```go
w.LoadFileAbs("simple.html")  // would convert it using filepath.Abs()
w.LoadFile(fullpath)  // would not
```

Or vice versa:

```go
w.LoadFile("simple.html")  // would implicitly convert it using filepath.Abs()
w.LoadPath(fullpath)  // would not
```

**Comment by mrg0lden** [comment]
Doing things implicitly isn't quite Go style of doing things, defining another function that does so is good though. 

But since this project is supposed to be quite tied to Sciter's API and behavior, I'm not sure.
