### ISSUE TITLE
how to cross compile from linux to window "sciter engine not found quitting"

### ISSUE THREAD

**Issue by younlok** [sciter-sdk/go-sciter#224]
so i cross compiled from linux to windows with this
`CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build  -ldflags "-extldflags -static" callback.go`

but when i run it in windows i just get sciter engine not found  quitting 
any solutions ??

**Comment by AshfordN** [comment]
sciter.dll must be in the same folder as the .exe file.
