### ISSUE TITLE
Can you provide Api related to the window

### ISSUE THREAD

**Issue by sohaha** [sciter-sdk/go-sciter#238]
Very convenient library, currently in use, can only get the relevant values of the screen and the `view.move` window operation through tiscript's `View.ScreenBox(# Workarea, # Rectw)`  but cannot be processed through go. Is there any plan for go version?

**Comment by pravic** [comment]
There is no such API in Sciter. However, you can use native OS API for that if tiscript doesn't suit you.

**Comment by sohaha** [comment]
Thanks for your reply, it seems that you can only use tis, after all, it is more troublesome to use os api to be compatible with multiple platforms
