### ISSUE TITLE
 window.DefineFunction causes memory leak

### ISSUE THREAD

**Issue by UnnoTed** [sciter-sdk/go-sciter#240]
In the video below you can see that when a `window.DefineFunction` is present it leaks memory.

First i test without `DefineFunction`, then with.
https://streamable.com/km49xr

I haven’t tested other Go fucntions.

Code:
https://sciter.com/wp-content/uploads/2020/07/leak.zip

**Comment by pravic** [comment]
I believe, it has something to do with the GC.

Could you test with the following? https://gist.github.com/pravic/e0468624cf79cb0e7d7d27f880d61698/revisions

**Comment by UnnoTed** [comment]
Running Go's GC between element changes prevents the memory from increasing further than the (`#b2`)big elements' ram usage, i'll do that in my app, thanks.

**Comment by pravic** [comment]
I mean, you don't have to run GC manually - eventually the memory will be freed anyway.
