### ISSUE TITLE
ARMv6 Support

### ISSUE THREAD

**Issue by ashfame** [sciter-sdk/go-sciter#241]
Hi, unable to find an answer to this, but does the project support ARMv6 architecture?

Building an open source air-gapped device. Hoping to be able to run on Raspberry Pi Zero (v1.3 which has no networking capabilities, but learnt today that browsers dropped support for ARMv6 long time ago. Any luck?

**Comment by pravic** [comment]
Better ask on sciter.com/forums.

**Comment by kekemuyu** [comment]
yes，it is support the pizerow. I had run the demo successfully on pizerow. You can surf the internet by usbthernet

**Comment by ashfame** [comment]
@kekemuyu Oh cool, but does it support JS or its own scripting language? I think its the latter. And my UI is a Vue.js app

Was hoping to replace the browser which runs the UI with a memory efficient alternative.

**Comment by kekemuyu** [comment]
> @kekemuyu  sciter is the smallest rander to run html5,others like github.com/zserge/lorca,it bind to chrome,you know its too large  to run for pizero.

**Comment by ashfame** [comment]
I had to give up on ARMv6 as memory constraints proved to be too much with the need of running a browser (mainly cuz my filesystem is ram based), so for now, I have given up on ARMv6 plan and currently using ARMv7 with 1 GB RPis.
