### ISSUE TITLE
Cant installl on linux

### ISSUE THREAD

**Issue by hcharlie1201** [sciter-sdk/go-sciter#247]
Im getting this error when i run ``` go get -x github.com/sciter-sdk/go-sciter ```

cgo1.go $WORK/b001/utils.cgo1.go $WORK/b001/_cgo_import.go
# github.com/sciter-sdk/go-sciter
../../../go/src/github.com/sciter-sdk/go-sciter/sciter.go:1052:142: cannot use _cgo1 (type *_Ctype_HWINDOW) as type **_Ctype_struct__GtkWidget in argument to _Cfunc_SciterGetElementHwnd

**Comment by pravic** [comment]
#245

**Comment by johto89** [comment]
edit go.mod file
step 1:
require github.com/sciter-sdk/go-sciter **v0.5.0** ----> require github.com/sciter-sdk/go-sciter **master**
step 2:
go mod tidy
step 3:
rerun program
