### ISSUE TITLE
Table hover bug

### ISSUE THREAD

**Issue by ACLzz** [sciter-sdk/go-sciter#252]
Hello, I think I found a bug with table element. Code, description and example are [here](https://github.com/ACLzz/sciter-table-bug).

Tell me if I doing something wrong or how to hot fix it please.

Maybe I can do it with tis script, I'm not good in js and tis, maybe you can write me example how to load rows to table via tis?

**Comment by ACLzz** [comment]
Can you help me? I still didn't figure out what's wrong

**Comment by pravic** [comment]
cc @c-smile

**Comment by c-smile** [comment]
You have broken table structure here: https://github.com/ACLzz/sciter-table-bug/blob/main/templates/passwords.html

The table should look like:

```
<table #passes>
     <thead>
          <tr>
                    <th>Title</th>
                    <th>Login</th>
                    <th>Email</th>
                    <th>Password</th>
                </tr>
      </thead>
      <tbody>
                <tr>
                    <td>Title<div class="cell-hover" #cell-hover><input type="button" value="Show"><input type="button" value="Copy"></div></td>
                    <td>Login<div class="cell-hover" #cell-hover><input type="button" value="Show"><input type="button" value="Copy"></div></td>
                    <td>Email<div class="cell-hover" #cell-hover><input type="button" value="Show"><input type="button" value="Copy"></div></td>
                    <td>Password<div class="cell-hover" #cell-hover><input type="button" value="Show"><input type="button" value="Copy"></div></td>
                </tr>
            </tbody>
            </table>
```

and you should add rows to the  `tbody` section.  HTML5 spec. mandates tbody element insertion if it is not present. And so, without explicit tbody, you are adding rows in a wrong place.

**Comment by ACLzz** [comment]
Oh thanks, never heard about `thead` and `tbody`. It works now. I think I need to learn more about html5. Thank you again

**Comment by pravic** [comment]
Thanks, Andrew!
