### ISSUE TITLE
How to set a window to the top and focus?

### ISSUE THREAD

**Issue by fuyoo** [sciter-sdk/go-sciter#255]
When I click on a tray icon, I create a new window that I want to bring to the top and focus. But I didn't find a way. How to operate it?

**Comment by pravic** [comment]
Well, Sciter uses `view.state = View.WINDOW_SHOWN` in script in [tray icon sample](https://github.com/c-smile/sciter-sdk/blob/master/samples/trayicon/trayicon-as-main-window.htm#L72).

If you want to do it using Go only - well, these methods need to be [implemented](https://github.com/sciter-sdk/go-sciter/tree/master/window).

**Comment by fuyoo** [comment]
Thank you ever so much.
