### ISSUE TITLE
sciter.go:1052:142: cannot use _cgo1 

### ISSUE THREAD

**Issue by antichown** [sciter-sdk/go-sciter#256]
github.com/sciter-sdk/go-sciter
../../go/src/github.com/sciter-sdk/go-sciter/sciter.go:1052:142: cannot use _cgo1 (type *_Ctype_HWINDOW) as type **_Ctype_struct__GtkWidget in argument to _Cfunc_SciterGetElementHwnd

go version go1.15.5 linux/amd64

**Comment by pravic** [comment]
#245

**Comment by antichown** [comment]
The module you wrote was really beautiful. But it does not work on the linux operating system and Golang version 1.15. Can you fix it, please?

**Comment by pravic** [comment]
Yes. It's going to be fixed, of course.
