### ISSUE TITLE
有哪个吊大的知道为何商业版源码编译出来的 sciter.static.lib 接近2GB.

### ISSUE THREAD

**Issue by ji4ozhu** [sciter-sdk/go-sciter#259]
有哪个吊大的知道为何商业版源码编译出来的 sciter.static.lib 接近2GB.
这也太大了吧?

**Comment by pravic** [comment]
https://sciter.com/forums/topic/build-sciter-lite-static-filesisz2gb/

**Comment by vanehu** [comment]
> 有哪个吊大的知道为何商业版源码编译出来的 sciter.static.lib 接近2GB. 这也太大了吧?

老板 你的代码咋买的啊  我都没看到哪里付款
