### ISSUE TITLE
win10编译之后中文乱码怎么解决?

### ISSUE THREAD

**Issue by Aquarian-Age** [sciter-sdk/go-sciter#263]
```
<meta charset="UTF-8"> 一直都在head内
```
这是用浏览器打开显示正常的
![Screenshot_20210106_231342](https://user-images.githubusercontent.com/36611556/103786328-468e6700-5077-11eb-9c52-eb51c8d74e8f.png)
下面两张是乱码的
![Screenshot_20210106_231431](https://user-images.githubusercontent.com/36611556/103786330-4726fd80-5077-11eb-8819-4baca1409e2f.png)
![Screenshot_20210106_231454](https://user-images.githubusercontent.com/36611556/103786333-48f0c100-5077-11eb-9b6c-54d3a1b46cc4.png)
用浏览器打开html文件显示是正常的

**Comment by nagasun** [comment]
文件保存为UTF8+BOM编码
