### ISSUE TITLE
BehaviorEvent: type conversion sets the 16th bit

### ISSUE THREAD

**Issue by mrg0lden** [sciter-sdk/go-sciter#267]
Hi, 
I tried to attach a behavior event handler on an element. When I tried to check its type by comparing it to existing enums, It didn't match the supposed types. Doing some investigations, I found that the 16th bit is set, so instead of (binary) `100` it becomes `10000000000100`.
<details>
<summary>Code Example</summary>
input is a *sciter.Element
### This code doesn't work

```go
//...
input.AttachEventHandler(&sciter.EventHandler{
			OnBehaviorEvent: func(target *sciter.Element, params *sciter.BehaviorEventParams) bool {
				cmd := uint32(params.Cmd())
				if cmd == uint32(sciter.EDIT_VALUE_CHANGED) {
					fmt.Println("It works, it seems")
				}
				fmt.Printf("%d %X %b\n", cmd, cmd, cmd)
				return true
			},
		})
//...
```

```go
input.AttachEventHandler(&sciter.EventHandler{
			OnBehaviorEvent: func(target *sciter.Element, params *sciter.BehaviorEventParams) bool {
				cmd := uint32(params.Cmd())
				leading := bits.LeadingZeros32(cmd)
				cmd ^= (1 << (31 - uint32(leading))) //remove leading set bit

				if cmd == uint32(sciter.EDIT_VALUE_CHANGED) {
					fmt.Println("It works, it seems")
				}
				fmt.Printf("%d %X %b\n", cmd, cmd, cmd)
				return true
			},
		})
````
</details>

Is this a normal behavior?

**Comment by pravic** [comment]
It's because of this: https://github.com/c-smile/sciter-sdk/blob/master/include/sciter-x-behavior.h#L73

**Comment by mrg0lden** [comment]
So I need to unmask it manually before checking its type, is that correct?

**Comment by pravic** [comment]
Correct.

Technically, we could introduce a separate `params.Phase()` and keep `params.Cmd()` clean.

**Comment by mrg0lden** [comment]
I think that'd be better because it's quite confusing now.
