### ISSUE TITLE
How to access DOM after calling window.Run?

### ISSUE THREAD

**Issue by jilieryuyi** [sciter-sdk/go-sciter#270]
求教，如题！

**Comment by jilieryuyi** [comment]
Update(true) 没有更新界面

**Comment by pravic** [comment]
English?

**Comment by jilieryuyi** [comment]
atfer call "Run" api,
win.Show()
win.Run()
use root.Append(element), how to reflesh window? Update(true) not work!!

**Comment by jilieryuyi** [comment]
use golang Append element

**Comment by pravic** [comment]
Could you show your code? 

Also, check examples: https://github.com/sciter-sdk/go-sciter/tree/master/examples

**Comment by jilieryuyi** [comment]
package main

import (
	"fmt"
	"github.com/sciter-sdk/go-sciter"
	"github.com/sciter-sdk/go-sciter/window"
	"log"
	"time"
)

var (
	win *window.Window
)


func tick() {
	go func() {
		startTime := time.Now()
		tick := time.NewTicker(time.Second)
		defer tick.Stop()
		for {
			select {
			case <- tick.C:
				root, err := win.GetRootElement()
				if root == nil {
					fmt.Println(err)
					continue
				}
				t, err := root.SelectFirst("#timer")
				if t == nil {
					fmt.Println(err)
					continue
				}
				t.SetText(fmt.Sprintf("%v", time.Since(startTime)))
				t.Update(true)
			}
		}
	}()
}

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()

	var err error
	sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SYSINFO)
	win, err = window.New(
		sciter.SW_TITLEBAR|
			sciter.SW_RESIZEABLE|
			sciter.SW_CONTROLS|
			sciter.SW_MAIN|
			sciter.SW_ENABLE_DEBUG, &sciter.Rect{
			Left:   0,
			Top:    0,
			Right:  500,
			Bottom: 600,
		})
	if err != nil {
		log.Fatal("Create Window Error: ", err)
	}
	win.SetTitle("some test")
	win.LoadFile("index.html")

	// UI will be blocked here. UI can't be displayed normally. Can I use the goroutine here?

	go tick()
	win.Show()
	win.Run()
}

**Comment by jilieryuyi** [comment]
`package main

import (
	"fmt"
	"github.com/sciter-sdk/go-sciter"
	"github.com/sciter-sdk/go-sciter/window"
	"log"
	"time"
)

var (
	win *window.Window
)


func tick() {
	go func() {
		startTime := time.Now()
		tick := time.NewTicker(time.Second)
		defer tick.Stop()
		for {
			select {
			case <- tick.C:
				root, err := win.GetRootElement()
				if root == nil {
					fmt.Println(err)
					continue
				}
				t, err := root.SelectFirst("#timer")
				if t == nil {
					fmt.Println(err)
					continue
				}
				t.SetText(fmt.Sprintf("%v", time.Since(startTime)))
				t.Update(true)
			}
		}
	}()
}

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()

	var err error
	sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SYSINFO)
	win, err = window.New(
		sciter.SW_TITLEBAR|
			sciter.SW_RESIZEABLE|
			sciter.SW_CONTROLS|
			sciter.SW_MAIN|
			sciter.SW_ENABLE_DEBUG, &sciter.Rect{
			Left:   0,
			Top:    0,
			Right:  500,
			Bottom: 600,
		})
	if err != nil {
		log.Fatal("Create Window Error: ", err)
	}
	win.SetTitle("稻壳图片上传工具")
	win.LoadFile("index.html")
	// UI will be blocked here. UI can't be displayed normally. Can I use the goroutine here?
	go tick()
	win.Show()
	win.Run()
}`

**Comment by jilieryuyi** [comment]
package main

import (
	"fmt"
	"github.com/sciter-sdk/go-sciter"
	"github.com/sciter-sdk/go-sciter/window"
	"log"
	"time"
)

var (
	win *window.Window
)


func tick() {
	go func() {
		startTime := time.Now()
		tick := time.NewTicker(time.Second)
		defer tick.Stop()
		for {
			select {
			case <- tick.C:
				root, err := win.GetRootElement()
				if root == nil {
					fmt.Println(err)
					continue
				}
				t, err := root.SelectFirst("#timer")
				if t == nil {
					fmt.Println(err)
					continue
				}
				t.SetText(fmt.Sprintf("%v", time.Since(startTime)))
				t.Update(true)
			}
		}
	}()
}

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()

	var err error
	sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SYSINFO)
	win, err = window.New(
		sciter.SW_TITLEBAR|
			sciter.SW_RESIZEABLE|
			sciter.SW_CONTROLS|
			sciter.SW_MAIN|
			sciter.SW_ENABLE_DEBUG, &sciter.Rect{
			Left:   0,
			Top:    0,
			Right:  500,
			Bottom: 600,
		})
	if err != nil {
		log.Fatal("Create Window Error: ", err)
	}
	win.SetTitle("some test")
	win.LoadFile("index.html")
	// UI will be blocked here. UI can't be displayed normally. Can I use the goroutine here?
	go tick()
	win.Show()
	win.Run()
}

**Comment by jilieryuyi** [comment]
````
package main

import (
	"fmt"
	"github.com/sciter-sdk/go-sciter"
	"github.com/sciter-sdk/go-sciter/window"
	"log"
	"time"
)

var (
	win *window.Window
)


func tick() {
	go func() {
		startTime := time.Now()
		tick := time.NewTicker(time.Second)
		defer tick.Stop()
		for {
			select {
			case <- tick.C:
				root, err := win.GetRootElement()
				if root == nil {
					fmt.Println(err)
					continue
				}
				t, err := root.SelectFirst("#timer")
				if t == nil {
					fmt.Println(err)
					continue
				}
				t.SetText(fmt.Sprintf("%v", time.Since(startTime)))
				t.Update(true)
			}
		}
	}()
}

func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()

	var err error
	sciter.SetOption(sciter.SCITER_SET_SCRIPT_RUNTIME_FEATURES, sciter.ALLOW_SYSINFO)
	win, err = window.New(
		sciter.SW_TITLEBAR|
			sciter.SW_RESIZEABLE|
			sciter.SW_CONTROLS|
			sciter.SW_MAIN|
			sciter.SW_ENABLE_DEBUG, &sciter.Rect{
			Left:   0,
			Top:    0,
			Right:  500,
			Bottom: 600,
		})
	if err != nil {
		log.Fatal("Create Window Error: ", err)
	}
	win.SetTitle("some test")
	win.LoadFile("index.html")
	// UI will be blocked here. UI can't be displayed normally. Can I use the goroutine here?
	go tick()
	win.Show()
	win.Run()
}
````

why ui block?

**Comment by pravic** [comment]
Because `Run()` function is synchronous and it is a loop essentially.

Use events instead. Also, you can access the DOM after `LoadFile()` but before `Run()`: https://github.com/sciter-sdk/go-sciter/blob/master/examples/insert/insert.go#L19

**Comment by jilieryuyi** [comment]
Do you have any examples of using events?

**Comment by jilieryuyi** [comment]
> Because `Run()` function is synchronous and it is a loop essentially.
> 
> Use events instead. Also, you can access the DOM after `LoadFile()` but before `Run()`: https://github.com/sciter-sdk/go-sciter/blob/master/examples/insert/insert.go#L19

Do you have any examples of using events?

**Comment by jilieryuyi** [comment]
> Because `Run()` function is synchronous and it is a loop essentially.
> 
> Use events instead. Also, you can access the DOM after `LoadFile()` but before `Run()`: https://github.com/sciter-sdk/go-sciter/blob/master/examples/insert/insert.go#L19

how to use Task in UI multi-goroutine?

**Comment by jilieryuyi** [comment]
https://github.com/sciter-sdk/go-sciter/issues/133  I found this
