### ISSUE TITLE
LockOSThread

### ISSUE THREAD

**Issue by c-smile** [sciter-sdk/go-sciter#278]
1. Windows shall be created in main GUI thread.
2. GUI thread may have multiple windows shown at the same time so having ```Run()``` as an instance method is not correct, IMO.

I am not sure but it makes sense to consider this approach:

https://github.com/golang/go/wiki/LockOSThread

**Comment by jqqjj** [comment]
Consider updating  codes like this: [https://github.com/lxn/walk/pull/493](https://github.com/lxn/walk/pull/493)
Otherwise app would crashes randomly when you are closing a dialog window.
Thanks.

**Comment by jqqjj** [comment]
`Exception 0xc0000005 0x1 0xc0004ade78 0x7ffc8351562d
PC=0x7ffc8351562d
signal arrived during external code execution

syscall.Syscall(0x7ffc83515420, 0x1, 0xc0004ade68, 0x0, 0x0, 0x0, 0x0, 0x0)
        D:/Go/src/runtime/syscall_windows.go:188 +0xe9
github.com/lxn/win.DispatchMessage(0xc0004ade68, 0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/lxn/win@v0.0.0-202011111058                                                             47-2a20daff6a55/user32.go:2324 +0x88
github.com/sciter-sdk/go-sciter/window.(*Window).Run(0xc0003aa790)
        C:/Users/Administrator/go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.1                                                             -0.20200602150116-89a4dd09b0f8/window/window_windows.go:65 +0x54`

**Comment by pravic** [comment]
#201 has suggested the same approach. We should probably do this.
