### ISSUE TITLE
drag-n-drop not working

### ISSUE THREAD

**Issue by coolit** [sciter-sdk/go-sciter#28]
The html file is as below:
https://github.com/c-smile/sciter-sdk/blob/master/samples/drag-n-drop/shell-file-drop.htm

How to make this custom-made Behavior work?

**Comment by oskca** [comment]
I have no idea now, I'll take a look later on

**Comment by coolit** [comment]
For your ref:
https://sciter.com/forums/topic/window-shell-drag-n-drop-with-golang/

**Comment by pravic** [comment]
I believe, it was fixed in f33043e.

cc #67
