### ISSUE TITLE
Example to update HTML from Go code...

### ISSUE THREAD

**Issue by deepesh-agarwal** [sciter-sdk/go-sciter#29]
Any example on how to dynamically update the HTML code from Go code, for example show progress events of a go process in a HTML progress-bar?

**Comment by Raggaer** [comment]
You just need to get the element from the window root element and just call your functions

`
func progressChannelHandler() {
	progressBarElement, err := rootElement.SelectFirst("#progress")
	if err != nil {
		log.Fatal(err)
	}
	for {
		select {
		case i := <-progressChannel:
			if err := progressBarElement.SetHtml(i, 0); err != nil {
				log.Fatal(err)
			}
		}
	}
}
`

This is what I use to update some label on my HTML I just do

`
progressChannel <- "Hello"
`

Hope it helps

**Comment by maojindao55** [comment]
Have a complete example?
