### ISSUE TITLE
Can sciter.js be used in the golang?

### ISSUE THREAD

**Issue by zyxk** [sciter-sdk/go-sciter#302]
Can sciter.js be used in the golang?
Can only use sciter.tis??
Is there a plan to support it?

**Comment by pravic** [comment]
Sciter.JS should work as is. Sciter.Tis should work as is. And, it seems, will be supported for a while and eventually dropped.

**Comment by zyxk** [comment]
My tests found that sciter.js cannot be applied to golang.
How does golang use sciter.js?
Is there a corresponding example?
Thank you very much.

**Comment by pravic** [comment]
Your tests are failing most likely due to #299.

**Comment by dzcpy** [comment]
So that means go-sciter doesn't support js?

**Comment by pravic** [comment]
Sorry, what do you mean?

**Comment by dzcpy** [comment]
I mean can I use js as script language with go-sciter?

**Comment by pravic** [comment]
Yes.

**Comment by zyxk** [comment]
> So that means go-sciter doesn't support js?

no, support js,  need use sciter-api branche
