### ISSUE TITLE
How does the "HTML" of go-sciter start to call js resources

### ISSUE THREAD

**Issue by zw9629** [sciter-sdk/go-sciter#326]
In my "go-sciter" project, html can load the js file correctly in both the browser and "scapp.exe" (windows), but in the "go run" or "go build", the js file cannot be loaded in the window
![image](https://user-images.githubusercontent.com/31214590/142709959-c6f35652-678c-4631-a2d1-87cf8286ba9f.png)
![image](https://user-images.githubusercontent.com/31214590/142710021-29ef7461-ea1f-47b5-887f-23d0335dfa22.png)

![image](https://user-images.githubusercontent.com/31214590/142710074-b297b6af-2598-40d7-82c9-6aaef7673e7c.png)
"Scapp.exe" on the left, "go run myapp" on the right
Can you help me

**Comment by pravic** [comment]
`window.LoadFile` must be provided with an absolute path. See https://github.com/sciter-sdk/go-sciter/blob/a04e052a28133d8a79c82b53fc861d1e473c0499/examples/demoes/01/demo1.go#L30-L34

**Comment by zw9629** [comment]
> `window.LoadFile `必须提供一个绝对路径。 看到
> 
> https://github.com/sciter-sdk/go-sciter/blob/a04e052a28133d8a79c82b53fc861d1e473c0499/examples/demoes/01/demo1.go#L30-L34

Thank you very much. The problem has been solved.
