### ISSUE TITLE
sciter.Value SetString got wired \u000

### ISSUE THREAD

**Issue by orangetangerine** [sciter-sdk/go-sciter#33]
in "sciter.go", func (pdst *Value) SetString
variable "chars" is utf16 of param str,
but "numChars" == len(str), which is the length of utf8(str).  (as I remember)

some language like Chinese will got unexpected "\u0000\u0000‎" at the end after SetValue and read from tiscript

I think it's a bug here

**Comment by orangetangerine** [comment]
func main() {
    src := "Go语言"
    lenSrc := len(src)
    lenUtf16 := len(utf16.Encode([]rune(src)))
    fmt.Println(lenSrc, lenUtf16)
}

a Chinese word in utf8 is 3 bytes length
English is alright because a letter is 1 byte

**Comment by orangetangerine** [comment]
I resolved this by simply adding a function in util.go

func StringToUTF16PtrWithLen(s string) (*uint16, int) {
	us, _ := Utf16FromString(s)
	length := len(us) - 1
	return &us[0], length
}

return the length.

and call it from func (pdst *Value) SetString(str string, uintType ...int)

**Comment by pravic** [comment]
It was fixed in #35
