### ISSUE TITLE
Sciter using outdated libcurl

### ISSUE THREAD

**Issue by fasa123** [sciter-sdk/go-sciter#36]
Appearently this uses an outdated version of libcurl? On Arch I get "Unable to load library: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found" when trying to running any of the examples. 

I am aware that this sciter issue obviously cannot be fixed here but maybe someone has an idea how to workaround this without having to use outdated libs. I mean is everyone who is using those bindings shipping outdated libcurls, and even if how do you perform the actual developement without using the outdated lib?

**Comment by fasa123** [comment]
I have searched for about 3 hours now and there is literally no way to obtain such outdated libcurls for Arch anymore. I have not found any at all. Is this project dead or do people simply not use this on Linux or is there a workaround I do not know of?

**Comment by oskca** [comment]
Well, the  sciter library for linux is most probably compiled on `Debian Linux` which I tried and this bindings works. The libcurl issue you met is related to the way how sciter was compiled (the dependency libraries are not statically included) since sciter is not an open source software perhaps you have to ask @c-smile for further help.

For the time being, I think the common platform for Sciter is still Windows:hushed:

**Comment by c-smile** [comment]
Sciter uses default libcurl.so supplied by the OS.
So you need to install it if your OS hasn't one already.
   
>  sudo apt-get install libcurl

or so,

**Comment by tejohnso** [comment]
It's using locating default libcurl, but it appears to be expecting specifically version 3.

>/usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/lib/sciter-gtk-64.so)

**Comment by tejohnso** [comment]
For Arch you can install libcurl-compat.
Then create a link to /usr/lib/libcurl-compat.so.4.4.0 in your oskca/sciter dir
`ln -s /usr/libcurl-compat.so.4.4.0 ./oskca/sciter/libcurl.so.4`
Then run your compiled binary using a temporary override of the library path
`LD_LIBRARY_PATH=[path-to-sciter-dir]:$LD_LIBRARY_PATH ./example-executable`

**Comment by c-smile** [comment]
I've updated sciter so it loads libcurl dynamically - of whatever version exists in the system.
