### ISSUE TITLE
Unable to load library

### ISSUE THREAD

**Issue by messheno** [sciter-sdk/go-sciter#37]
the compilation I have a type error: sciter-x-api.c Unable to load library: /tmp/go-build517969141/command-line-arguments/_obj/exe/sciter-gtk-64.so: cannot open shared object file: No such file or directory on archlinux and fedora 24. Thank you for your help.

**Comment by Raggaer** [comment]
Missing runtime stuff? Did you link towards the sdk?

**Comment by pravic** [comment]
See #63.
