### ISSUE TITLE
Can't set value of progress bar

### ISSUE THREAD

**Issue by kuznetsovin** [sciter-sdk/go-sciter#38]
Don't work function `SetValue`, my PR #34 fix this function for correct work.

**Comment by Raggaer** [comment]
I also tried `SetAttr` but no success

**Comment by Raggaer** [comment]
Did you try to call `Update` after changing the attribute?

**Comment by Raggaer** [comment]
Wont work even with calling `Update(true)`

**Comment by pravic** [comment]
#34 was merged.
