### ISSUE TITLE
Does not working on Linux/Ubuntu16.04

### ISSUE THREAD

**Issue by seitbekir** [sciter-sdk/go-sciter#41]
I've tried to install for few days this things, but cannot run or compile nothin because of error below.

``` bash
# github.com/oskca/sciter/window
../github.com/oskca/sciter/window/window_linux.go: In function ‘gwindow’:
../github.com/oskca/sciter/window/window_linux.go:8:9: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘GtkWidget * {aka struct _GtkWidget *}’ [-Wformat=]
  printf("hwnd:%d\n", hwnd);
         ^
```

I thought, that the trouble is in unsupported things and reinstalled GTK3. Moved SDK files into go $PATH -- no result.

I am new it this and really want to use it for my small project. Maybe some help for me, because, no answers in google.

**Comment by seitbekir** [comment]
I've configurated via `pkg-config --cflags gtk+-3.0`, `pkg-config --libs gtk+-3.0` (but didn't worked before). And It didn't show any error on install. On run shows:
```bash
[/home/seitbekir/go-dev/work/src/github.com/oskca/sciter/sciter-x-api.c] Unable to load library: /home/seitbekir/go-dev/work/bin/sciter-gtk-64.so: cannot open shared object file: No such file or directory
exit status 1
```

**Comment by Raihli** [comment]
This is "just" a warning, but after the file don't run if you don't have the sciter-gtk-64.so file in the folder.

Solution:
`wget https://github.com/c-smile/sciter-sdk/raw/master/bin.gtk/libsciter-gtk-64.so -O sciter-gtk-64.so`

**Comment by pravic** [comment]
Check [updated instructions](https://github.com/sciter-sdk/go-sciter#getting-started), also I've made small fixes for Linux. Works now.

**Comment by pravic** [comment]
See #63.
