### ISSUE TITLE
packfolder

### ISSUE THREAD

**Issue by lovellshn** [sciter-sdk/go-sciter#52]
I want to use the ui resources by packfolder, how can i use it?which use it in c++ like this below:
sciter::archive::instance().open(aux::elements_of(resources));  
SciterLoadFile(hWnd, L"this://app/index.html");

**Comment by AllenDang** [comment]
same question, it's really blocks me to use sciter if I cannot pack them into a executable at MacOS.

**Comment by Raggaer** [comment]
Maybe we can use https://github.com/jteeuwen/go-bindata. Not sure if you can make Sciter load a file by its byte array tho

**Comment by Raggaer** [comment]
You can use go-bindata. Use `Load` and it will work fine.

**Comment by pravic** [comment]
Also go-sciter supports [go.rice](https://github.com/GeertJohan/go.rice) out of box.

**Comment by pravic** [comment]
And packfolder since #86 and #141.
