### ISSUE TITLE
windows build Warning: resolving _SciterHostCallback_cgo by linking to _SciterHostCallback_cgo@8

### ISSUE THREAD

**Issue by CodyGuo** [sciter-sdk/go-sciter#54]
go env
set GOARCH=386
set GOBIN=D:\go\bin
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\gopath
set GORACE=
set GOROOT=D:\go
set GOTOOLDIR=D:\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

go version go1.7.4 windows/386

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/TDM-GCC-32/bin/../libexec/gcc/mingw32/5.1.0/lto-wrapper.exe
Target: mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=mingw32 --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --disable-symvers --enable-cxx-flags='-fno-function-sections -fno-data-sections -DWINPTHREAD_STATIC' --prefix=/mingw32tdm --with-local-prefix=/mingw32tdm --with-pkgversion=tdm-1 --enable-sjlj-exceptions --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm-1)

go build warring:
# github.com/oskca/sciter
Warning: resolving _SciterHostCallback_cgo by linking to _SciterHostCallback_cgo@8
Use --enable-stdcall-fixup to disable these warnings
Use --disable-stdcall-fixup to disable these fixups
Warning: resolving _SciterElementCallback_cgo by linking to _SciterElementCallback_cgo@8
Warning: resolving _LPCWSTR_RECEIVER_cgo by linking to _LPCWSTR_RECEIVER_cgo@12
Warning: resolving _LPCSTR_RECEIVER_cgo by linking to _LPCSTR_RECEIVER_cgo@12
Warning: resolving _LPCBYTE_RECEIVER_cgo by linking to _LPCBYTE_RECEIVER_cgo@12
Warning: resolving _KeyValueCallback_cgo by linking to _KeyValueCallback_cgo@12
Warning: resolving _ElementEventProc_cgo by linking to _ElementEventProc_cgo@16
Warning: resolving _ELEMENT_COMPARATOR_cgo by linking to _ELEMENT_COMPARATOR_cgo@12

**Comment by pravic** [comment]
Well, I believe that this has gone already.
