### ISSUE TITLE
update to Sciter v4 needed or not ?

### ISSUE THREAD

**Issue by ffred60** [sciter-sdk/go-sciter#57]
Hello all,

just begin to read Sciter docs and looking here to use it with Go, but didn't tried anything yet.
I saw that Sciter is now at v4.x, but it's indicate here a support of v3.3.03.

is it a problem ? should I search to download an old Sciter version ? should I wait for an update of oskca/sciter ? is there an update planned..??

thanks.
ffred

**Comment by pravic** [comment]
Hi.

I just did a v4 compatibility changes for [pysciter](https://github.com/pravic/pysciter/commit/b3749700f32f4c537e2998a7cb31e5fae02b7248#diff-b67e3c21df30e31a0826b3fdb359b8b2R100).

At least you need to change a SCITER_DLL_NAME for [Windows version](https://github.com/oskca/sciter/blob/master/include/sciter-x-types.h#L93), because Golang bindings uses [Tailered Sciter C Headers](https://github.com/oskca/sciter#the-tailered-sciter-c-headers), which are outdated now.

**Comment by ffred60** [comment]
Hi Pravic,
thanks a lot for looking at it..
doing things with win32api for now, but will come back to Sciter soon.
nice work for pysciter !
ffred

**Comment by pravic** [comment]
I have updated headers to the recent Sciter version, currently it sits in v4 branch: https://gopkg.in/sciter-sdk/go-sciter.v4.

Samples work well, however I haven't ported new API, like [GetSciterGraphicsAPI](https://github.com/c-smile/sciter-sdk/blob/master/include/sciter-x-graphics.h), [GetSciterRequestAPI](https://github.com/c-smile/sciter-sdk/blob/master/include/sciter-x-request.h), [SciterProcX](https://github.com/c-smile/sciter-sdk/blob/master/include/sciter-x-msg.h). And note about new `sciter.dll` convention: https://sciter.com/starting-sciter-v-4-series/

I'd be glad if someone tested new version.

cc @oskca

**Comment by ffred60** [comment]
Hi, 
great news, thanks 👍 
not sure I will have time for that in the next few days (and don't forget I'm new to it), but will try to do things as soon as I can.
thanks again.
ffred

**Comment by pravic** [comment]
Lets leave it opened until someone have a look on v4 version.

**Comment by ffred60** [comment]
ok, sorry..

**Comment by ffred60** [comment]
Hi,
did a very rapid test with go-sciter on Windows 8.1 64bits with the included examples.
so, I :
`go get github.com/sciter-sdk/go-sciter`
also renamed sciter.dll to sciter64.dll and put it in the path.

all seems to work well, except for two examples :
- Handlers : got error messages about rice.
looking at rice.go, it was lacking an import line :
	`github.com/GeertJohan/go.rice`
and of course, I had to :
`go get github.com/GeertJohan/go.rice`
then it was ok..

- TextHtml : no window opened, all the output goes to the console.
don't know if that was on purpose, but since there is a window created with a title added it doesn't seem normal to me.
so, just add those two lines at the end and it was ok :
```
w.Show()
w.Run()
```
will try to take more time later to test with my own things...
ffred

**Comment by pravic** [comment]
You've checked out an old version.

Try to use these instructions: https://github.com/sciter-sdk/go-sciter/issues/59#issuecomment-278945989

**Comment by ffred60** [comment]
ok, sorry my bad, I went too fast..

but now there's a problem.
tried it quickly again yesterday before leaving work on the same computer (with the "wrong" package still installed) and it worked good. (no more problem with the "Handlers" example. still the same with "TextHtml" but that's not a package problem).
I wanted to take some more time this morning at home (Win10 computer, but don't mind), so installed with :
`go get gopkg.in/sciter-sdk/go-sciter.v4`
and nothing worked.
the problem is that the "wrong" package from "github.com/sciter-sdk/go-sciter" is not installed on this computer and several places in the new package are still importing the old package !!
you can even see it in your post  from #59 :
```
...
$ go build -v .
github.com/sciter-sdk/go-sciter
github.com/sciter-sdk/go-sciter/window
gopkg.in/sciter-sdk/go-sciter.v4/examples/simple
```
see the lines with "github.com/sciter-sdk/go-sciter" ?

so import lines need to be changed in all the examples and at least in "gopkg.in\sciter-sdk\go-sciter.v4\window" from the files window.go and window_windows.go.
after that it seems ok..
sorry didn't have time to look more at it. there are probably similar imports in files for the other platforms.


_one more thing but that's more on my side because I don't know yet how to work with that.
I needed to rename the sciter dlls to "sciter.dll" (not sciter32 or sciter64.dll anymore), like what they are named now in sciter4 SDK to make it work. and since I want to be able to compile my code for 32 or 64 bits it seems easier to me before because I could simply put the two DLLs with my code during development and don't think about it. will see later how to work with that..._

**Comment by pravic** [comment]
Okay, it seems, its better to merge v4 branch into the master to eliminate thoase issues with import.

As for sciter32.dll - I agree, it was better name than now. It seems, half of users want to have unique name (no idea why) and other prefer the old way. You can ask on forum about it.

**Comment by pravic** [comment]
V4 was merged into master.

**Comment by ffred60** [comment]
ok, thanks.. will see later on the forum about the DLL naming.
_also the readme.md should be changed about the DLL naming in the "getting started" section._

just looked at how it's called in "sciter-x-api.c" for the windows part (with the old version still present in comment for sciter32 or sciter64.dll) maybe it could suits everyone by looking first for sciter32 or sciter64 and if not present looking for sciter.dll..?
but that's another "problem", will think more about that and learn how it's usually done with Go, maybe there's a simple solution I don't know yet. will add the info here later if I find something..

**Comment by pravic** [comment]
> maybe it could suits everyone by looking first for sciter32 or sciter64 and if not present looking for sciter.dll..?

Sounds reasonable, but it needs manual copying of those libraries.

**Comment by ffred60** [comment]
yes, those willing to use "sciter.dll" will stay with the standard sciter SDK and use the dll as they want.
those like me who prefer sciter32 & sciter64.dll will have to rename the dll before using it and put it in the PATH or simply in the code directory. really not a big deal..
