### ISSUE TITLE
Sciter bindings maintenance discussion

### ISSUE THREAD

**Issue by pravic** [sciter-sdk/go-sciter#58]
Hi there,

According to your attention ad:

> This project is not maintained for a quite long time and is looking for a new project owner or some active contributors.

May it would be better to create organization for [Sciter bindings](https://sciter.com/developers/sciter-sdk-bindings/) and transfer our repositories there?

Also it would be easier to accept PRs, for example. I was going to update your Go bindings, but now I think that its even better to collect all repositories in single place.

cc @c-smile @pravic @midiway @da-baranov @oskca 

Update: https://github.com/sciter-sdk here it is.

**Comment by pravic** [comment]
cc @Mikanoshi

**Comment by oskca** [comment]
It's would be great, and I like to change the project name to `go-sicter` the same time :smile:

**Comment by oskca** [comment]
Project transferred, but how can now change the project name?

**Comment by Mikanoshi** [comment]
How to transfer repo to this Sciter SDK?

**Comment by pravic** [comment]
![image](https://cloud.githubusercontent.com/assets/724639/22697170/b543769a-ed61-11e6-9fb7-7225afe01241.png)

**Comment by Mikanoshi** [comment]
Done)

**Comment by oskca** [comment]
@pravic Can you change the project name now ?

**Comment by pravic** [comment]
@oskca Done.

**Comment by oskca** [comment]
:+1:

**Comment by oskca** [comment]
I'v just correct the import path for this new repo and dit the `git push`.

Shall I do this directly or via some PR process?

**Comment by pravic** [comment]
Directly, for sure. Its your repo :)

**Comment by midiway** [comment]
good idea @pravic  👍

**Comment by pravic** [comment]
@Mikanoshi How come you have leaved and [took your repo](https://github.com/sciter-sdk/SciDe/commit/4a9a923e7012d8946f6b96475a65fba01238717b)? o_O Without a word..

**Comment by Mikanoshi** [comment]
You just noticed? 😃 If I remember correctly I wasn't satisfied with the permissions, couldn't change things I wanted to change, so I moved.

**Comment by Mikanoshi** [comment]
I emailed you and maybe posted on sciter.com forum (don't remember) - no response. I like full control of my fork anyway :)

**Comment by oskca** [comment]
Sure, i'm ok with that-------- 原始邮件 --------主题：Re: [sciter-sdk/go-sciter] Sciter bindings maintenance discussion (#58)发件人：pravic 收件人：sciter-sdk/go-sciter 抄送：oskca ,Mention @oskca Hi, long time no see.
Do you want to transfer Nim bindings under the same root? https://github.com/oskca/nsciter
