### ISSUE TITLE
Update element attribute

### ISSUE THREAD

**Issue by Raggaer** [sciter-sdk/go-sciter#61]
I am trying to update a progress bar value attribue

`<progress value="10" max="100"></progress>`

In Go I am doing the following (cutted some parts to make it simple)

```go
// Get element name by its ID from the HTML
htmlElement, err := root.SelectById(ele.ID)

if err != nil {
	continue
}

// Set element attribute
if err := htmlElement.SetAttr(ele.Attr, ele.Val); err != nil {
	logger.Error.Fatalf("Cannot set element attribute: %v", err)
}


// Update element so changes take effect
if err := htmlElement.Update(true); err != nil {
	logger.Error.Fatalf("Cannot update element: %v", err)
}
```

the `ele` variable is just an struct and with the following data

```go
type HtmlAttr struct {
	ID string
	Attr string
	Val string
}
```

I am getting no errors from the code but the progress bar isnt getting the new value displayed..

**Comment by pravic** [comment]
Hey,

There is an ambiguity between *attributes*, *states* and *values* of HTML elements. [Attributes](https://sciter.com/docs/content/sciter/Attributes.htm) used to initialize the *initial* state of element, and you should use [Element](https://sciter.com/docs/content/sciter/States.htm) states to change its runtime visual *state* (like disabled/enabled, collabsed/expanded and so on). And *value* [property](https://sciter.com/docs/content/sciter/Element.htm) is used to keep (and render) element's value (like text/number in text boxes, position in sliders and progress bars and so on).

You can read more here: http://stackoverflow.com/a/6004028/736762

So, if you need to change the value of element, use `func (e *Element) SetValue` for that.

**Comment by pravic** [comment]
And yes, you do not need to call the Element.Update explicitly — usually element reflects and redraws its state himself.

**Comment by Raggaer** [comment]
Thanks @pravic 

Using `SetValue` works fine

**Comment by maojindao55** [comment]
@Raggaer is there  a setValue demo?
