### ISSUE TITLE
how to create an html window ?

### ISSUE THREAD

**Issue by ffred60** [sciter-sdk/go-sciter#62]
Hi,
how can I create a custom html window, without the native window frame ?
like those here : [https://sciter.com/html-window/](https://sciter.com/html-window/)

if I use `window.new` like in the included examples, I always got the native window frame.
I want to create a window like in the sciter SDK samples, in "dialogs+windows".
for example in "test-dialog.htm", the "sample-dialog-custom-frame-solid-with-shadow" window.

thanks..

**Comment by pravic** [comment]
Via script:
`view.dialog` or `view.window` (see [View docs](https://sciter.com/docs/content/sciter/View.htm))

Via native code:
`SciterCreateWindow` or by WinAPI / GTK / Cocoa.

**Comment by ffred60** [comment]
sorry, but I don't get it..
I saw the `view.dialog` examples in sciter SDK, but if I want my main window to be  a custom html window how can I create it from Go..?

**Comment by pravic** [comment]
Check [examples](https://github.com/sciter-sdk/go-sciter/tree/master/examples/simple) folder.

**Comment by pravic** [comment]
Check [window creation flags](https://github.com/sciter-sdk/go-sciter/blob/d723fce252fa9fd1e60a856d581680026576f292/types.go#L12), you need to create the borderless native window and then load an html with specified `window-frame` attribute.

**Comment by ffred60** [comment]
_yes, sorry. I validate my first post before I finished to write it..._
yep..! 👍    :-)
just did a rapid test before going to work, but with SW_ALPHA is working.
Thanks !

**Comment by pravic** [comment]
Actually ou don't have even edit your window creation, just specify `window-frame`. Good luck :)
