### ISSUE TITLE
missed uchar.h on windows 10 + msys2

### ISSUE THREAD

**Issue by ringrid** [sciter-sdk/go-sciter#65]
env: win10+msys2

$ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/6.3.0/lto-wrapper.exe
目标：x86_64-pc-msys
配置为：/msys_scripts/gcc/src/gcc-6.3.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
线程模型：posix
gcc 版本 6.3.0 (GCC)

--------------------------------------------

errors with "go get":
 $ go get -x github.com/sciter-sdk/go-sciter
WORK=C:\msys64\tmp\go-build001650022
mkdir -p $WORK\github.com\sciter-sdk\go-sciter\_obj\
mkdir -p $WORK\github.com\sciter-sdk\
cd E:\projects\go\imports\src\github.com\sciter-sdk\go-sciter
CGO_LDFLAGS="-g" "-O2" "C:\\Go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "C:\\msys64\\tmp\\go-build001650022\\github.com\\sciter-sdk\\go-sciter\\_obj\\" -importpath github.com/sciter-sdk/go-sciter -- -I "C:\\msys64\\tmp\\go-build001650022\\github.com\\sciter-sdk\\go-sciter\\_obj\\" -g -O2 -g -w -std=c11 -Iinclude -DPLAIN_API_ONLY -Iinclude -Iinclude sciter.go sciter_windows.go types.go utils.go
# github.com/sciter-sdk/go-sciter
In file included from include/sciter-x.h:20:0,
                 from E:\projects\go\imports\src\github.com\sciter-sdk\go-sciter\sciter.go:11:
include/sciter-x-types.h:30:21: fatal error: uchar.h: No such file or directory
   #include <uchar.h>
                     ^
compilation terminated.

**Comment by pravic** [comment]
In general, uchar.h should be shipped for C11.

**Comment by ringrid** [comment]
I had resolve this question，it miss some runtime. I had added. thx
pacman -S mingw-w64-x86_64-toolchain base-devel

**Comment by pravic** [comment]
Great
