### ISSUE TITLE
DPI Aware for windows ?

### ISSUE THREAD

**Issue by codehz** [sciter-sdk/go-sciter#66]
![image](https://cloud.githubusercontent.com/assets/13158903/24583528/b6eaf48a-177f-11e7-9635-64967925b26a.png)
Can it support DPI Aware for windows?

**Comment by codehz** [comment]
The sciter's demo is support this feature...so I think the same feature could be also supported in this binding
(120dpi 125%)
![image](https://cloud.githubusercontent.com/assets/13158903/24583534/1ece5c72-1780-11e7-857f-453033e014f4.png)

**Comment by pravic** [comment]
As I know, dpi aware can be set either by manifest or by runtime call. You can add it to your code.

**Comment by pravic** [comment]
[Sciter's code](https://github.com/c-smile/sciter-sdk/blob/master/demos/sciter/main.cpp#L24), [manifest](https://github.com/c-smile/sciter-sdk/blob/master/demos/sciter/res/dpi-aware.manifest).

**Comment by codehz** [comment]
I just add this, and it worked. I think it should be called by library...
```
SetProcessDpiAwareness, err := dll.FindProc("SetProcessDpiAwareness")
if err != nil {
	log.Fatal(err)
}
SetProcessDpiAwareness.Call(1)
```

**Comment by ZeronoFreya** [comment]
I found a way to solve：

`
import "syscall"
syscall.NewLazyDLL("Shcore.dll").NewProc("SetProcessDpiAwareness").Call(uintptr(2))
`

[SetProcessDpiAwareness](https://www.codegists.com/code/disintegration/)
