### ISSUE TITLE
Printing with a printer not working.

### ISSUE THREAD

**Issue by josephbudd** [sciter-sdk/go-sciter#67]
Windows-10.

Sciter.exe:
Select printer and Print work when loading sciter-sdk/samples/printing/pager-demo.htm in sciter.exe.

Go-sciter:
 * Select printer works.
 * Print does not work.
 * No errors are reported.

So I copied the files and folders from the sciter-sdk/samples/printing folder into the go src folder.
I wrote a simple main.go to load the file pager-demo.htm and run the window.
The file loads and sciter runs. The select printer works, showing the old xp select printer but the print does not work. No errors show up in the inspector.

Also I just downloaded the latest sciter sdk from github with the same results.

Also I tried the same thing with sciter-sdk/samples/printing and rust-sciter and the printer function worked properly.

**Comment by josephbudd** [comment]
**My Bad!**

The print method is working perfectly in my app now. I am clueless as to why it didn't! Totally clueless!

**Comment by josephbudd** [comment]
It wasn't working. That was the select printer window. Its still now working.

**Comment by pravic** [comment]
> Print does not work. No errors are reported.

Confirm. It doesn't work in Python bindings too. I'll look what's wrong.

**Comment by pravic** [comment]
It turned out that [OLE initialization](https://msdn.microsoft.com/en-us/library/windows/desktop/ms690134(v=vs.85).aspx) is required for proper printing support.
