### ISSUE TITLE
Let windows app have sciter.dll in the same folder as the exe.

### ISSUE THREAD

**Issue by josephbudd** [sciter-sdk/go-sciter#71]
* I made the edits shown below to sciter-x-api.c
 * I rebuilt go-sciter
 * I copied sciter.dll into the folder with my .exe file.
 * Now my windows apps load sciter.dll from the current working directory.

**sciter-x-api.c:**

  * adding `#include <string.h>`
  
 * then starting at line 19 
```
#elif defined(WINDOWS)

    ISciterAPI* SAPI( ISciterAPI* ext ) {
       static ISciterAPI* _api = NULL;
       if( ext ) _api = ext;
       if( !_api )
       {
          char* cwd;
          char buff[1024];
          cwd = getcwd( buff, 1024 );
          strcat(buff, "\\sciter.dll");
          HMODULE hm = LoadLibrary( TEXT(buff) );

```

**Comment by pravic** [comment]
What was wrong before your patch?

> Let windows app have sciter.dll in the same folder as the exe.
> Now my windows apps load sciter.dll from the current working directory.

It is a default Windows behavior, that is how [LoadLibrary](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx) works. Check [Dynamic-Link Library Search Order](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx), it loads DLL from:

1. The directory from which the application loaded (_that is exe directory_).
2. The current directory (_your modification_).
3. The system directory.
And so on.

**Comment by josephbudd** [comment]
Oh crap, I'm sorry. I apologize for wasting your time.

**Comment by pravic** [comment]
:)
