### ISSUE TITLE
Feature-request: in binary runtime

### ISSUE THREAD

**Issue by dwall80** [sciter-sdk/go-sciter#72]
Hey, thanks for the great package and introduction to Sciter. Amazing!!

I was wondering if it would be possible to read the dll (or whichever runtime we're using) out from binary data. I'm currently using go-bindata with go-sciter (only noticed rice later) and i am deploying the dll with my app by reading from bin data and writing to file. Just wondering if there is any way I could load the dll in memory and avoid the write to file.

Apologies if my question is naive I only have a little familiarity with c. I think this would be a great feature if feasible.

**Comment by pravic** [comment]
In general it is not possible to use DLL directly from memory, as well as .so and .dylib libraries in other platforms. Of course, it can be achieved via some hacks, but still, it is no-go way.

On the other side, Sciter can be used as a [static library](https://sciter.com/prices/), so you can build a completely stand-alone application.

**Comment by dwall80** [comment]
Thanks for the quick response. 

I haven't done much working with c from go (always with dlls). So if I went for a license that allowed for static linking (which seems pretty reasonable) would it still be possible to call from my existing go code via go-skiter and compile into a single binary or would I need to embrace the c to make that work?

**Comment by pravic** [comment]
> or would I need to embrace the c to make that work?

I am not sure. If licensed sciter will be shipped as a static library, so you just need to change one line in go-sciter to disable DLL search and to add one flag for CGO to link the static library. I can add static library support for go-sciter as well.

If licensed sciter shipped as sources (not compiled yet), so, apparently, you need to compile it first. A bit more complicated, but not an obstacle.
