### ISSUE TITLE
Close  button  disappear

### ISSUE THREAD

**Issue by Orefa** [sciter-sdk/go-sciter#74]
doc：
SW_CONTROLS   = (1 << 4), // has minimize / maximize buttons

but，
not use SW_CONTROLS，the Close button will disappear

**Comment by pravic** [comment]
Any minimal example to reproduce? Sciter version?

**Comment by Orefa** [comment]
I am using the latest version
 https://github.com/c-smile/sciter-sdk
    9945e912bb271f28516eb81afd5a1d6b046213ad

**Comment by pravic** [comment]
Ah, I see what you mean. I forwarded your question to forum: https://sciter.com/forums/topic/sw_controls-question/

**Comment by c-smile** [comment]
I’d suggest to use SW_CONTROLS style and remove those buttons individually from script: 
```
view.windowMinimizable = false;
view.windowMaximizable = false;

```
Yet see [HTML Window](https://sciter.com/html-window/) article.

**Comment by pravic** [comment]
Guess, you've got your answer :)
