### ISSUE TITLE
How to avoid output 2017/07/18 18:35:53 finalizing el 0x & {93f5f20 0}????

### ISSUE THREAD

**Issue by xingcuntian** [sciter-sdk/go-sciter#76]
go version go1.7.3 windows/amd64

2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 0}

**Comment by pravic** [comment]
Thanks, there were some unnesessary logs, I've removed them.
