### ISSUE TITLE
Calling defined functions as strings

### ISSUE THREAD

**Issue by dwall80** [sciter-sdk/go-sciter#77]
Hi, I'm not sure if this is a bug your end, an issue with Sciter or just a big understanding fail on my side:

I am defining a function on the go side:

```
        window.DefineFunction("TestFunc", func(args ...*sciter.Value) *sciter.Value {
		log.Println("Called TestFunc")
		return sciter.NewValue("TestFunc here")
	})
```

Now from the client side (tiscript) the following works:

```
        var msg = view.TestFunc();
        view.msgbox(msg);

```
So far, so good. The problem comes when i try to access the function using a string name:

If the function were defined client side then one of the following would work:

```
        var msg = view.root["TestFunc"]();
        view.msgbox(msg);
```

or

```
        var msg = self.ns["TestFunc"]();
        view.msgbox(msg);
```

but these result in an error (because the func is bound to view I presume):

> “WrongType: undefined, unexpected instance of function” 

so i tried various other things with no success:

```
        var msg = self.ns["view.TestFunc"]();
        view.msgbox(msg);
```

```
        var msg = view["TestFunc"]();
        view.msgbox(msg);
```

but no Joy, an ideas on this one?

**Comment by pravic** [comment]
Howdy.

First of all, I would suggest you to check documentation for [Element](https://sciter.com/docs/content/sciter/Element.htm) and [View](https://sciter.com/docs/content/sciter/View.htm) classes to eliminate really wrong attempts like `view.root["TestFunc"]` or `view["TestFunc"]`.

`view` is like `window` in JS, but it does not equal to it and does not contain all functions - instead, they contained in the document namespace which can be accessed via `.ns` property of the root `<html>` element (and root element itself can be accessed via `view.root` or `self` or even by `$(html)` selector).

As for the main part of your question - I assume that you have asked it already [in forum](https://sciter.com/forums/topic/how-to-call-a-defined-function-from-a-string/#post-52371) :)

**Comment by dwall80** [comment]
Hey Pravic, thanks for your help on both sides. 

I have dumped the contents of self.ns, this contains all my functions declared on the tiscript side, but none of the functions that I declared from GO using windows.DefineFunction() - I think what I'm missing is where these methods end up. Do they actually get placed within any namespace in tiscript? 

I was looking through the go code, and they are all loaded into s.eventMapper.scriptingMethodMap[name], so Im thinking these functions might be called in dynamically by an event handler rather than actually being present in the namespace.

The comment above the function states that they are within the View namespace (which makes sense since I can call via view.TestFunc(), so, if I understand correctly (please do correct me if wrong) I should be able to access via view.root.ns.prototype.View["TestFunc"] but that View is a null object (based on this way of accessing namespace - https://sciter.com/forums/topic/namespace-defined-in-script-overrides-namespace-and-contents-defined-in-native/). 

So as you stated root ns can be access with view.root.ns, so maybe I can access view namespace like this:
view.root.ns.View (no, doesnt work)
or this
view.root.View (no, doesnt work)

I'm running out of ideas here. I know what namespace it *should* be in (View). I have been given several way of accessing a namespace and none seem to return a result for View. Is it time to give up and duplicate all my function on the client side (its looking like the quicker (if dirtier) option at this point) 

Any final suggestions before I give up?

**Comment by pravic** [comment]
Ah, now I get it, sorry for misunderstanding.

All answers above were about functions defined by scripts inside HTML, but you are talking about native handlers.

`DefineFunction` just adds a callback to the list (actually, map) of native handlers (see [wrapper.go](https://github.com/sciter-sdk/go-sciter/blob/master/wrapper.go#64)). You can read about native handlers and Sciter behaviors at "Behaviors and event handling" section in https://sciter.com/developers/embedding-principles.

So, saying in pseudo language:

```javascript
  // tiscript side
  view.TestFunc();
  view.UnknownFunc();
```


```cpp
// native side
bool sciter::event_handler::handle_scripting_call(hElement, params)
{
  switch(params.name)
  {
  case "TestFunc": 
    printf("native: TestFunc was called\n";
    break;
  case "AnotherFunc":
    ...
    break;
  default:
    printf("native: unknown function `%ws` with %d args\n", params.name, params.argc);
    return false;
  }
  return true;
}
```

In Go it works as the following:
```go
func (e *eventMapper) toEventHandler() *EventHandler {
...
	OnScriptingMethodCall: func(he *Element, params *ScriptingMethodParams) bool {
		if nf, ok := e.scriptingMethodMap[params.Name()]; ok {
			params.Return(nf(params.Args()...))
			return true
		}
		return false
	},
```

So, back to the your question: you want to call a particular native method by its name? There is no such way. You can access tiscript **native methods** defined by tiscript class/method definitions (see tiscript.h) like `view.msgbox` or `String.println`, but you can not access DOM **native handlers**, you can only call them.

You need to reorganize your code somehow.

**Comment by pravic** [comment]
> You need to reorganize your code somehow.

For example, define only one native function:
```go
w.DefineFunction("dispatch", func(args ...*sciter.Value) *sciter.Value {
  switch (args[0].String()) {
    "TestFunc": // do something with Test
    "AnotherFunc": // do something with Another
  ...
}
```

```javascript
var incomingFunctionName = "TestFunc";
view.dispatch(incomingFunctionName, args);
```

**Comment by dwall80** [comment]
Thanks for confirming and clarifying. 

I was hovering around the idea that this wasn't possible as it was going via the event Mapper. I will do as suggested and wrap them into a switch statement on a generic function. Thanks for the time spent.
