### ISSUE TITLE
How to load `utf8 encoded` html file

### ISSUE THREAD

**Issue by shawnye** [sciter-sdk/go-sciter#80]
For go-sciter/examples/simple

When build and load utf8 encoded html file (contains Chinese characters for example), the GUI shows the messy code.

How to load utf8 encoded html file ?
Thanks

**Comment by pravic** [comment]
You should save it with BOM I guess.

**Comment by shawnye** [comment]
No, I use pure utf-8 file without BOM. 

You can try it by copying these characters to your  utf8-encoded html file: `中文`

**Comment by pravic** [comment]
As I said, try to save HTML *with* BOM:

[screenshot](http://c2n.me/3MRfBIc.png)

**Comment by shawnye** [comment]
Thanks 

I would try to make my editors( Visual Studio Code, Jetbrains webstorm,...)  to support utf8 with BOM
