### ISSUE TITLE
How to remove all child elements in golang code

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#82]
I have find Insert() this method.

**Comment by pravic** [comment]
`Element.clear` in TIScript. The same via native api, but it seems, go-sciter lacks it.

**Comment by pravic** [comment]
Added it. You need to update go-sciter from this repository again.

**Comment by TongxiJi** [comment]
ok.And append()  ?

**Comment by pravic** [comment]
Yeah.

These methods were missed because @oskca implemented only C API, but `Element.Clear` and `Element.Append` are implemented as inline functions in C++.

**Comment by TongxiJi** [comment]
Hmmmmmm.I see.
Recently i'll  submit  more issues .I'd like to wirte something use pure golang.
But sometimes i had to use tiscript.

**Comment by pravic** [comment]
Okay, feel free to contact me about it.
