### ISSUE TITLE
loadfrom file as a temple element

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#83]
Hello maybe we can have a method  like " sciter.LoadFromFile(filename string)(* Element,err error)".So we can use it as a template.

**Comment by pravic** [comment]
Template? Go doesn't have templates, does it?

**Comment by TongxiJi** [comment]
now  we can use sciter.CreateElement  to create a element ，
but i want to create a  complete  from a file such as  xxxx-cell-item.htm.

**Comment by pravic** [comment]
Well, technically you can do the following: create element, load html file in memory and assign html to the element. If it's what you want, you can do it.

**Comment by TongxiJi** [comment]
I see，and you mean this method “func (e *Element) SetHtml(html string, where SET_ELEMENT_HTML) error”？

**Comment by pravic** [comment]
Yep

**Comment by TongxiJi** [comment]
Well ，ty.
