### ISSUE TITLE
CreateElement  OnClick not work

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#84]
```
addon_li_div_del, _ := sciter.CreateElement("div", "")
		addon_li_div_del.SetAttr("class", "list-icon-delete")
		addon_li.Append(addon_li_div_del)
		addon_li_div_del.OnClick(func() {
			log.Println("OnClick")
			addon_li.Delete()
		})
```

**Comment by pravic** [comment]
I guess, you have to attach element first, because Sciter allows only limited set of operations with freshly created element.

For example, you can temporary attach element somewhere in `<head>`, do what you want, and then move it to its destination. Or attach to destination right after creating.

**Comment by TongxiJi** [comment]
But  ‘addon_li’ has been attached.

**Comment by pravic** [comment]
> addon_li.Append(addon_li_div_del)

Sorry, I missed that. Ok, need to check then.

**Comment by TongxiJi** [comment]
Additionally，'addon_li'  is also  a create element by code， and has been attached to the root, and can be previewed.

**Comment by pravic** [comment]
Ah, I see. Not every element can be clicked in Sciter.
If you want a `<div>` which can be clicked, you have to make it [clickable](https://sciter.com/docs/content/behaviors/clickable.htm):

```css
list-icon-delete {
  behavior: clickable;
}
```

And I strongly suggest to test HTMLs in Sciter app itself (if it possible) with its inspector. 

And, if there any reason to play with DOM at native side? It is low level and requires much more code and attention. Isn't it easier to work with UI in script and call Go only for high level operations?

**Comment by TongxiJi** [comment]
LoL,it works.You are right.
