### ISSUE TITLE
"github.com/lxn/win"  is no longer support windows xp

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#85]
Now "github.com/lxn/win"  is no longer support windows xp and i have try it.

**Comment by pravic** [comment]
"Now" - since when? We can fork that repository and stick to version with XP support. May be.

**Comment by TongxiJi** [comment]
see this.
https://github.com/lxn/win/issues/32

**Comment by TongxiJi** [comment]
And  several issues of "github.com/lxn/win" about windows xp  may be helpful.

**Comment by TongxiJi** [comment]
LOL,it works now.
