### ISSUE TITLE
how to protect static resource?

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#88]
images htmls  etc..

**Comment by midiway** [comment]
protect? what do you mean? to make people not be able to steal your code?

**Comment by xeonel2** [comment]
I think he meant making the assets not easily accessible on the install directory

**Comment by pravic** [comment]
Then one can use ZIP archive, Sciter archive (check bin/packfolder), [go.rice](https://github.com/GeertJohan/go.rice) or anything else - just override loading routine and provide asset's data from anywhere.

**Comment by xeonel2** [comment]
Wow thanks I didn't even have to search for the topic. Now I just need to find the optimal way to do that

**Comment by TongxiJi** [comment]
But i cant find method like "SciterLoadFile" in golang port.
And how to load image from ZIP archive?

**Comment by TongxiJi** [comment]
> All relative links inside that file will be resolved against content of the zip. So if you have <img src=”images/img1.png”> then its URl will be resolved to artificial
…/content.zip/images/img1.png and the image will be loaded from the zip.

done.


But where is the method like "SciterLoadFile" in golang port.

**Comment by pravic** [comment]
[LoadFile](https://github.com/sciter-sdk/go-sciter/blob/b89464628412e54e6c3d4554e04ee7d799987f9a/sciter.go#L130).

**Comment by TongxiJi** [comment]
Hmmmm, also the same .
Thanks a lot.

**Comment by TongxiJi** [comment]
I just tried the ZIP archive and BLOB type in golang , but it did not work.
Someone tried successfully?

**Comment by zhuwei** [comment]
楼主，有找到解决办法吗？主要是图片。。。

**Comment by pravic** [comment]
@zhuwei See the [comment above](https://github.com/sciter-sdk/go-sciter/issues/88#issuecomment-327190518).

**Comment by zhuwei** [comment]
@pravic Thanks very much.
