### ISSUE TITLE
elementl.Attr(string) panic

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#89]
use elementl.Attr(string)  to get the value ,
but panics with index out of bounds.

**Comment by pravic** [comment]
A bit more details? OS, Sciter version, html code to reproduce (or does it always happen and everywhere?)

**Comment by TongxiJi** [comment]
ui：
`    <button id="native"  data-type="1">Native Handler Button</button>`

golang：
`	el, err := root.SelectFirst("#native")
	if err == nil {
		el.Attr("data-type") //panic: runtime error: index out of range
	}`

**Comment by pravic** [comment]
Thanks, I'll look on it.

**Comment by pravic** [comment]
Fixed, download a new version from the github.
