### ISSUE TITLE
Can't run any of the examples - Linux Mint 18

### ISSUE THREAD

**Issue by DazedNConfused-** [sciter-sdk/go-sciter#90]
After setting everything up according to the Readme file, trying to run any of the examples results in an immediate crash.

**Command**: `~/go/src/github.com/sciter-sdk/go-sciter/examples/simple $ go run simple.go`
**Output**: 

> SIGILL: illegal instruction
> PC=0x7efc4d9beaab m=0 sigcode=2
> signal arrived during cgo execution
> 
> goroutine 1 [syscall, locked to thread]:
> runtime.cgocall(0x496bb0, 0xc42004fe98, 0xc)
>         /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004fe68 sp=0xc42004fe28
> github.com/sciter-sdk/go-sciter._Cfunc_SciterLoadFile(0x2686370, 0xc42000c520, 0x0)
>         github.com/sciter-sdk/go-sciter/_obj/_cgo_gotypes.go:987 +0x4a fp=0xc42004fe98 sp=0xc42004fe68
> github.com/sciter-sdk/go-sciter.(*Sciter).LoadFile.func1(0x2686370, 0xc42000c520, 0xc42000c520)
>         /home/lopezg/go/src/github.com/sciter-sdk/go-sciter/sciter.go:133 +0x6a fp=0xc42004fed0 sp=0xc42004fe98
> github.com/sciter-sdk/go-sciter.(*Sciter).LoadFile(0xc42000c500, 0x4d0ba0, 0xb, 0x0, 0x0)
>         /home/lopezg/go/src/github.com/sciter-sdk/go-sciter/sciter.go:133 +0x54 fp=0xc42004ff38 sp=0xc42004fed0
> main.main()
>         /home/lopezg/go/src/github.com/sciter-sdk/go-sciter/examples/simple/simple.go:16 +0xb8 fp=0xc42004ff88 sp=0xc42004ff38
> runtime.main()
>         /usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc42004ffe0 sp=0xc42004ff88
> runtime.goexit()
>         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0
> 
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
>         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
> 
> rax    0x1
> rbx    0x0
> rcx    0x27d9310
> rdx    0x27d42d0
> rdi    0x27ece80
> rsi    0x0
> rbp    0x0
> rsp    0x7fff29bc24c0
> r8     0x27d9310
> r9     0x27d42e8
> r10    0x1b09
> r11    0x7efc4d8d0590
> r12    0x7fff29bc28a0
> r13    0x0
> r14    0x7fff29bc2880
> r15    0x7fff29bc2890
> rip    0x7efc4d9beaab
> rflags 0x10202
> cs     0x33
> fs     0x0
> gs     0x0
> exit status 2

**Additional information**:

`~/go/src/github.com/sciter-sdk/go-sciter/examples/simple $ gcc --version`

> gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`~/go/src/github.com/sciter-sdk/go-sciter/examples/simple $ go version`

> go version go1.8.3 linux/amd64

**Comment by pravic** [comment]
Are you able to run the examples in the Sciter sdk itself on this OS? From sciter-sdk/bin.gtk?

**Comment by DazedNConfused-** [comment]
No. After setting the executable bit on the examples, attempts to run any of them result in the following output: 

`/opt/desa/sciter-sdk/bin.gtk $ ./uminimal64 `
> Illegal instruction

It may be an OS related problem with the Sciter SDK itself.

**Comment by pravic** [comment]
Then it is better to report on https://sciter.com/forums. Also share 
your OS and CPU information.

**Comment by pravic** [comment]
Well, as it [turned out](https://sciter.com/forums/topic/cant-run-any-of-the-examples-linux-mint-18-ubuntu-16-04/), the problem is in SSE4.1 absence, because Sciter requires it currently,  but it may be relaxed in future. Nothing we can do here though.
