### ISSUE TITLE
Linking a html button and Go toghether

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [sciter-sdk/go-sciter#91]
How can I make a HTML button run a function in GO

**Comment by pravic** [comment]
This can be achieved by two ways:

1) Better way: register window handler (via [window.DefineFunction](https://github.com/sciter-sdk/go-sciter/blob/master/examples/handlers/handlers.go#L26-L32)) and call it from script by `view.YourFunction(args)`
2) Lower level way: subscribe to the click event of the button (via [element.OnClick](https://github.com/sciter-sdk/go-sciter/blob/master/examples/handlers/handlers.go#L59-L65)).

**Comment by AlmightyFloppyFish** [comment]
"view.YourFunction(args)" is javascript right? So i do something like this in go:
window.DefineFunction(func somefunc() {Do something})

and then in Javascript:
view.somefunc()
?

**Comment by pravic** [comment]
Correct. But it's not Javascript, it is called Tiscript.
