### ISSUE TITLE
cannot find package "github.com/GeertJohan/go.rice" 

### ISSUE THREAD

**Issue by carusyte** [sciter-sdk/go-sciter#93]
My "hello world" code with go-sciter failed to run and I got this error message, 

      imports github.com/sciter-sdk/go-sciter/rice
      imports github.com/GeertJohan/go.rice: cannot find package "github.com/GeertJohan/go.rice" in any of:
      /usr/local/go/src/github.com/GeertJohan/go.rice (from $GOROOT)
      .../go/src/github.com/GeertJohan/go.rice (from $GOPATH)

The dependent `GeertJohan` is broken?

**Comment by pravic** [comment]
Works for me. Any [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example)?

**Comment by gcstang** [comment]
I had the same error and had to manually run 
`go get github.com/GeertJohan/go.rice`
