### ISSUE TITLE
Unable to load library: dlopen(/private/var/.../sciter-osx-64.dylib, 5): image not found

### ISSUE THREAD

**Issue by carusyte** [sciter-sdk/go-sciter#94]
In OSX, I've installed the sciter-sdk 64 bit version and exported both `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` environment variables in my .bash_profile, but each time I run my "hello world" mini program in `GoLand` IDE, I encountered this error message:

    [sciter-x-api.c] Unable to load library: dlopen(/private/var/folders/fb/phz99gmn7cld34rh4f6ppmlw0000gn/T/../../../sciter-osx-64.dylib, 5): image not found

I investigated the file `sciter-x-api.c` and found the following code:

            ...
            void* lib_sciter_handle = dlopen(SCITER_DLL_NAME, RTLD_LOCAL|RTLD_LAZY);
            if( !lib_sciter_handle ) {
                const char* lookup_paths[] =
                {
                    "/" SCITER_DLL_NAME,
                    "/../Frameworks/" SCITER_DLL_NAME, // - (bundle folder)/Contents/Frameworks/
                    "/../../../" SCITER_DLL_NAME // aside of bundle folder (SDK samples)
                };
                for( int n = 0; !lib_sciter_handle && n < 3; ++n ) {
                    char tpath[PROC_PIDPATHINFO_MAXSIZE];
                    strcpy(tpath,folderpath);
                    strcat(tpath, lookup_paths[n]);
                    lib_sciter_handle = dlopen(tpath, RTLD_LOCAL|RTLD_LAZY);
                }
            }
            if (!lib_sciter_handle) {
                fprintf(stderr, "[%s] Unable to load library: %s\n", __FILE__, dlerror());
                exit(EXIT_FAILURE);
            }
            ...

It seems that the scope of `lookup_paths[]` is quite limited and doesn't value the environment variable `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH`. Can it be extended or am I using this lib correctly?

**Comment by carusyte** [comment]
For now I copied the `sciter-osx-64.dylib` file to my project root and it worked. Sorry to disturb if I miss some points in the instruction.

**Comment by gcstang** [comment]
@carusyte if you want to use the setting "DYLD_LIBRARY_PATH" you need to add that path in GoLand to your run config inside there using the Environment section on the first tab.  Otherwise by default (and I just found this out myself from pravic, you need to add it to the golang project you're working on and it will just find it).
