### ISSUE TITLE
"sciter engine not found" after windows compile

### ISSUE THREAD

**Issue by rawsh** [sciter-sdk/go-sciter#95]
Using the simple example. 

`env GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build`

When I use `wine res.exe` I get an error saying "sciter engine not found, quitting"

**Comment by huasheng28** [comment]
I had a same problem with you, and i do somethings blow:
unzip the `sciter-sdk.zip`
add `~\sciter-sdk\bin\32` to your Environment variables, if you're using 64-bit version,then change it
delete the `sciter.dll` which you put in system32 folder
restart your windows

this is worked for me, you can try it.

**Comment by pravic** [comment]
Well, it was under Linux (Wine), but yes - the Wine has its Environment settings as well. Or simply put  a corresponding sciter.dll near your executable.
