### ISSUE TITLE
Global callback handlers not called on heavy load or when calling frame.load() (at least on 64 bit systems)

### ISSUE THREAD

**Issue by dwall80** [sciter-sdk/go-sciter#96]
Ive been experiencing a number of issues with my global resource call handler going AWOL. This issue initially surfaced as 404s being returned from resource loads [sciter forum issue](https://sciter.com/forums/topic/404s-from-golang-registered-callbacks/) 

I have since refactored my app to simplify the issue and this is what I'm seeing now: 

As a first step I re-organised my assets as follows (note references to suggested refactors were from Andrew on Sciter forum):

ui/
–template.html
–splash.html
–style/
—-img/
–script/

This structure seems to be most compatible with relative routes – I load an initial splash page using load file and once some processes are complete I call LoadFile again to load the template page as follows:

```
err := w.window.LoadFile(w.rscPrefix + templateHTMLFile)
if err != nil {
	w.Error(err)
}
```
where w.rscPrefix + templateHTMLFile == asset://ui/template.html

A quick note on this; I had to add the ui/ element to the path as without it my relative paths (e.g css/my.css) would resolve to:
asset://template.html/css/my.css – this feels like a bug to me but perhaps not, either way works with ui ele in path

My next step was to try to load the content into a frame as suggested. From what you said previously my understanding is the frame should be a full html doc and can contain head links to css/script.

So I created a simple namespaced template.tis as follows:

```
namespace Template {

    var Content = $(#content);

    function LoadFrame(name){
        view.Log("LoadFrame: " + name + ".html");
        try{
            var loaded = Content.load(self.url(name + ".html"));
            view.msgbox(String.printf("loaded: %v , %v", loaded, self.url("ui/"+ name + ".html")));
            

        }catch(e){
            view.msgbox(e.message);
        }
    }
}
```
note: the path to the asset is as I would expect: asset://ui/welcome.html but this just returns false and never loads anything, there are no hits to my resource handler on the golang end.

Now thanks to my new file structure i can do as you suggested and replace the rscPrefix with a call to the file directly – If I do this everything works fine so the question is why is my resource handler not being called when calling load on an element. here is where it is registered:

```
func (rh *ResourceHandler) RegisterResources(w *window.Window) {
	h := &sciter.CallbackHandler{
		OnLoadData: func(ld *sciter.ScnLoadData) int {
			log.Println("data resource call", ld.Uri())
			return rh.LoadData(ld)
		},
	}

	w.SetCallback(h)
}
```
the log of “data resource call” for the asset loaded into the frame element never get called and these binding are take care of by the sdk, my app is doing nothing else at this time, there is nothing that could be occupying Sciter. Furthermore, if you notice view.Log is called immediately before the load attempt, this is also registered as a callback, similar to resource handler and this works just fine.

Is this something I can deal with or is this a bug in the golang-sdk wrapper?
Im about ready to bypass sciters loading again and just use my own callback – which seems to work consistently but will cause pain with eval tiscript again. I strongly suspect the route handler callbacks going AWOL may be the cause of my previous 404s

**Comment by dwall80** [comment]
I think I am seeing a few separate issues her. I have built a clean demo of the issue of calling load from a frame in tiscript here: [load from frame issue](https://github.com/dwall80/sciter-issue) - the load function never hits the golang SCN_LOAD_DATA handler

Andrew from Sciter took a look and seemed to think it was due to uint32 c types being mapped to arch dependent golang ints: https://github.com/sciter-sdk/go-sciter/blob/master/types.go#L874

I had a go a t mapping the c.UINT to uint32, it all compiled but didn't solve the issue for me (though my knowledge of cgo is pretty poor) Would be much appreciated if you could take a look.

**Comment by pravic** [comment]
I believe it might be fixed in #97.

As for your point to the types.go - that particular case doesn't have such problem since the `ScnLoadData` is coming from the CGO (as `C.SCN_LOAD_DATA`) which used the C's `UINT` (defined in [include/sciter-x-typex.h](https://github.com/sciter-sdk/go-sciter/blob/master/include/sciter-x-types.h#L209).

However I found more places with wrong types in that file. I fixed them also. And I would appreciate if you downloaded a new version and did some tests against it.

**Comment by dwall80** [comment]
Thanks, I will give it a go and let you know

**Comment by dwall80** [comment]
Hey Pravic - took a while to test as everything else started breaking on me (dep update doesnt work on win64 at the moment) and because I updated all my dependencies I also discovered that github.com/lxn/win on which this project depends is also now broken (broken in commit two days back)

However I am please to say that as long as you acquire a working commit of lxn/walk your fix has indeed resolved the issue. 

Thank you for your help

**Comment by dwall80** [comment]
UPDATE:
frame.load is generally working as expected for me now - I am noticing that I still have load failures under some scenarios, for example, if I load a master CSS I see issues with frames calling resources - but I think it will be more helpful if I can create a simple test case and open a new issue. 

I am often a little confused as to where to go first with issues (here or sciter/go forums - which is better for you?)
