### ISSUE TITLE
when use latest version of  github.com/lxn/win  ,it not work.

### ISSUE THREAD

**Issue by TongxiJi** [sciter-sdk/go-sciter#98]
When using then latest version of  github.com/lxn/win  ，it not works now.
1. Backup your github.com/lxn/win and update “github.com/lxn/win” to the newest version.
2.run any sciter demo.

**Comment by dwall80** [comment]
I opened this issue for this: https://github.com/lxn/win/issues/39 - opened in a rush - it would be helpful to flesh out the details a bit

**Comment by ericdgit** [comment]
I'm having similar problems (I think). I'm on windows 10, and with a GoLand IDE.

```
panic: The specified procedure could not be found.
goroutine 1 [running]:
github.com/lxn/win.MustGetProcAddress(0x7ff9c5670000, 0x4f34c5, 0xe, 0x7ff9c568fef0)
	C:/[mypath]/src/github.com/lxn/win/win.go:57 +0x7d
github.com/lxn/win.init.1()
	C:/[mypath]/src/github.com/lxn/win/comctl32.go:253 +0x191
github.com/lxn/win.init()
	<autogenerated>:1 +0x5e
github.com/sciter-sdk/go-sciter.init()
	<autogenerated>:1 +0x66
main.init()
	<autogenerated>:1 +0x50
```

**Comment by TongxiJi** [comment]
lxn/win  fixed now
