### ISSUE TITLE
.SetOption(sciter.SCITER_SET_GFX_LAYER,4) Do not work

### ISSUE THREAD

**Issue by LibiChai** [sciter-sdk/go-sciter#99]
hello  , I use `xxx.exe -sciter-fgx=skia` , It can work;

but this code  is  do not work
```golang
w,err := .......
.....
w.SetOption(sciter.SCITER_SET_GFX_LAYER,4)
```

please help me fix it  ,thank you !

**Comment by pravic** [comment]
That should be called before any window creation.

**Comment by LibiChai** [comment]
if i dont create windows,how i get sciter.Sciter ?

**Comment by pravic** [comment]
Yeah, it lacks this at the moment :)

**Comment by LibiChai** [comment]
Can you help me with the field sample code abou this? Thank you very much

**Comment by pravic** [comment]
Could you try the latest version?  I haven't checked it, but it should work as following:

```go
func main() {
  sciter.SetOption(sciter.SCITER_SET_GFX_LAYER, sciter.GFX_LAYER_SKIA);
  sciter.SetOption(sciter.SCITER_SET_DEBUG_MODE, 1);
  sciter.SetOption(sciter.SCITER_SET_UX_THEMING, 1);

  w, err := window.New ...
```

**Comment by LibiChai** [comment]
it not work, because SetOption is a method, belong to srtuct *sciter.Sciter. 
shoud i new this struct ?

**Comment by LibiChai** [comment]
Thank you very much,I have see your commit. 😁

**Comment by pravic** [comment]
So, it works? Great then :+1:

**Comment by LibiChai** [comment]
There have a compile error  `..\github.com\sciter-sdk\go-sciter\sciter.go:397:` cannot convert 0 (type int) to type C.HWND` 
I try fix  `hwnd := C.HWINDOW(0)` to `hwnd := C.HWINDOW(nil)`
It can finish compile. but I can't be sure if it's useful.

**Comment by pravic** [comment]
Check it now.

**Comment by LibiChai** [comment]
well done! I have try this ,It works very well. Thank you!

**Comment by pravic** [comment]
My pleasure :)
